### ISSUE TITLE
missing text

### ISSUE THREAD

**Issue by bakaneko718** [teachingtechYT/teachingtechYT.github.io#102]
might just be me, but im on chrome and the letters or numbers either dont show up or after a refresh they do, but not in the fill boxes. even if i highlight the area it doesnt show.

**Comment by teachingtechYT** [comment]
Can you reply with a screenshot please? You can paste in right into the text box.

**Comment by bakaneko718** [comment]
of course like bringing a car to a mechanic... the issue is gone... if it happens again i'll post a screenshot. sorry for the bother.

**Comment by teachingtechYT** [comment]
No problem, please reopen if you can replicate.
