### ISSUE TITLE
Slicer Flow Calibration Text

### ISSUE THREAD

**Issue by Azariah98** [teachingtechYT/teachingtechYT.github.io#103]
On https://teachingtechyt.github.io/calibration.html#flow I am looking at the settings for top layer thickness in Cura 4.6.1. Step 3 of the guide says "Shell > Top thickness: 0". In my version of Cura, 'Top Thickness' is a subsetting of 'Top/Bottom Thickness', both of which are in mm rather than layers. The actual Top Thickness value is grayed out and set to the Top/Bottom Thickness value. There is a subsetting of Top Thickness called Top Layers that I can edit. This is measured in actual layers. I can set this to zero. 

This wasn't too difficult to figure out, but it does differ from what is in the guide. I'm not sure if this is just my installation of Cura or not. Maybe it's an updated interface?

**Comment by teachingtechYT** [comment]
I have updated the instruction to more closely match. Thank you.
