### ISSUE TITLE
404 file not found

### ISSUE THREAD

**Issue by witorwitor** [teachingtechYT/teachingtechYT.github.io#108]
After clicking download gcode in retraction calibration I am just getting an error in a new pop up window with 'error 404 file not found'

**Comment by teachingtechYT** [comment]
I am unable to reproduce this.
It should be impossible as a 404 comes when requesting a file that can't be found, whereas clicking the button creates the file on the fly using javascript.
Perhaps there is something in your browser security settings disabling javascript?
