### ISSUE TITLE
[FR] Add support for .x3g files. 

### ISSUE THREAD

**Issue by sloth865** [teachingtechYT/teachingtechYT.github.io#113]
Creator Pro doesnt take .gcode files, takes .x3g files instead. Cant use the calibration website.

**Comment by teachingtechYT** [comment]
My site starts with gcode and then modifies it with javscript to produce gcode. The best I could do is add a link to a converter if you know one.

**Comment by teachingtechYT** [comment]
Closed pending a solution for converter.
