### ISSUE TITLE
First Layer Calibration not respecting Delta bed diameter

### ISSUE THREAD

**Issue by eford321** [teachingtechYT/teachingtechYT.github.io#118]
First Layer calibration is exceeding the bed diameter. For example, when setting "0,0 at centre of bed (Delta):" and a diameter of 300mm. The first X move in the resulting gcode is to X-165.364.  The maximum move should not exceed -150.00.

Gcode file is attached:

[firstlayer.txt](https://github.com/teachingtechYT/teachingtechYT.github.io/files/5145512/firstlayer.txt)

**Comment by teachingtechYT** [comment]
I have the same result. It seems the gcode preview in Simplify3D is inaccurate for deltas. Will fix, in the meantime consider lowering your diameter by 50-60 mm as a temporary workaround.

**Comment by teachingtechYT** [comment]
Fixed, thanks for finding.
