### ISSUE TITLE
Baseline GCode fails with Prusa Mk3S + MMU2S

### ISSUE THREAD

**Issue by wcraigtrader** [teachingtechYT/teachingtechYT.github.io#119]
The generated baseline.gcode file always includes this at the start of the first layer, after any custom Gcode:

```
T0
G92 E0.0000
```

Unfortunately, on a Prusa Mk3S with the MMU2S, the additional `T0` will cause the MMU to hang. The only way around this is to edit the generated Gcode and comment out the extraneous `T0`. I would suggest adding an additional checkbox for multi-head printers to delegate tool selection to the custom header section.

**Comment by teachingtechYT** [comment]
Implemented!
T0 now commented out if the box is ticked.
