### ISSUE TITLE
Feature Request - Dropdown menu of printers

### ISSUE THREAD

**Issue by Partins** [teachingtechYT/teachingtechYT.github.io#122]
I was doing the bed leveling tutorial and when generating the GCODE one has to choose the build area. it would be nice if there was a dropdown menu with at least the most popular printers. It's a small thing and the users wouldn't have to google the size of the buildplate every time.

**Comment by teachingtechYT** [comment]
I'm sorry but I disagree with this. The amount of work required to implement printers into a drop down vs the user looking in their slicer/google for the bed dimensions is disproportionate. You only have to enter the values once, and they are automatically stored across tabs and browser refreshes.
The whole site is geared towards being convenient but users still have to be willing to put in some effort. Enter two numbers once is such a trivial thing, I feel it is an entirely reasonable commitment.
