### ISSUE TITLE
temp tower failures - underextrusion?

### ISSUE THREAD

**Issue by ornery-atmosphere** [teachingtechYT/teachingtechYT.github.io#132]
Not sure whats going on but i can't get the temp tower to print much past the second tier. have tried about 6 times and the stepper motor just stops, I am able to print other temp towers and other models and have no issues at all with them, just this temp tower. Ender 3 pro 1.1.4 silent board, dual gear extruder, otherwise stock.
Fantastic site btw. such a great resource for newbies and the more experienced.

**Comment by teachingtechYT** [comment]
Any chance of a pic and posting the gcode to filebin.com ?
The only thing that stands out about your setup in the Creality silent board, which aren't compatible with linear advance. Enabling it can cause the extruder stepper to stop responding mid print. I doubt you've gone this way though?

**Comment by ornery-atmosphere** [comment]
Yeah I can post up a pic and put the Gcode there for you later tonight . I don't have linear advance on. Not even sure how to turn it on yet. I didn't realise linear advance it wasn't compatible with the silent board, bummer. On 2 Sep 2020 5:07 pm, teachingtechYT <notifications@github.com> wrote:
Any chance of a pic and posting the gcode to filebin.com ?
The only thing that stands out about your setup in the Creality silent board, which aren't compatible with linear advance. Enabling it can cause the extruder stepper to stop responding mid print. I doubt you've gone this way though?

**Comment by ornery-atmosphere** [comment]
https://filebin.net/zu8y0os5iyc9o318 there is the gcode.
![20200902_210010](https://user-images.githubusercontent.com/65491013/91977338-af7c7000-ed61-11ea-9dd9-3d8ff4484fb8.jpg)

**Comment by Cappytano** [comment]
Up your extrusion. Just realized this issue. It's in the Gcode generator. If your multiplier is say, .92....increase your extrusion within, say Simplify3d during the print to 108%.

**Comment by migxmac** [comment]
I think I'm running into this issue as well.
I uploaded the generated gcode to the online [gcode viewer](gcode.ws) and it estimates I'll use -29 mm of filament!
![TemperatureTowerForDelta_200-225](https://user-images.githubusercontent.com/6003480/93639059-074fe380-f9be-11ea-8faa-4347f9661b48.png)

The generated gcode(changed type to .txt for upload)
[temperature_tower_200_225.txt](https://github.com/teachingtechYT/teachingtechYT.github.io/files/5247836/temperature_tower_200_225.txt)
:

**Comment by teachingtechYT** [comment]
All of the tests have been tweaked in a coming update. There's nothing to address this because it's a rare problem but more emphasis will be placed on explaining the use of M221 in the custom start gcode to address this.

**Comment by ornery-atmosphere** [comment]
awesome thank, just to let you know the problem disapeared when i changed from the stock creality firmware to my own build of marlin 2.0 bugfix

________________________________

**Comment by teachingtechYT** [comment]
Glad to hear you found a fix. There's so many variations in firmware it's *almost* impossible to keep up.
