### ISSUE TITLE
[FR] Z-hop in subsequent tests

### ISSUE THREAD

**Issue by kromeninja** [teachingtechYT/teachingtechYT.github.io#135]
Hi! Would it be possible to add Zhop as an option in the Temperature Tuning calibration, as we previously calibrate it within the retraction area, I feel like those chosen settings should be able to be then carried over to the next test which is Temperature Tuning.

**Comment by teachingtechYT** [comment]
It can be done and I'd like to add it to the subsequent tests. Only trouble is it's not a fun job as currently a lot of manual changes need to take place. I need to write a script to automate this given more nozzle size/layer height combinations are on the way.

**Comment by teachingtechYT** [comment]
And by the way the test does have z hop enabled currently, I think 0.4 mm from memory.

**Comment by teachingtechYT** [comment]
Z hop is being added to every test in a big update later this week.
