### ISSUE TITLE
Is the acceleration testing object printed rotated by 90 degrees? [Note needed]

### ISSUE THREAD

**Issue by lmamakos** [teachingtechYT/teachingtechYT.github.io#136]
I might be misinterpreting things, but when I print the acceleration test generated gcode, the side with the "X" character is printed on along the Y axis (bed moving front to back on my Ender 3).  The side with the "Y" characters is printed along the X axis.

![2020-09-06 00 41 52](https://user-images.githubusercontent.com/1544466/92318402-f07eb980-efd9-11ea-9875-a22998e4f901.jpg)

Maybe this is traditionally how this object is printed, first time I've encountered it.  But the faces are not labeled in the same way as, e.g., a typical 20mm calibration cube.

**Comment by teachingtechYT** [comment]
This is the intended behavior and I need to add a note explaining.

My logic is that vibration from the y axis is actually shown on the X side. Visualise the Y moving back and forth in your head and hopefully you'll agree.

**Comment by teachingtechYT** [comment]
I'm adding a video to the bottom of that page this week to further explain.
