### ISSUE TITLE
Inconsistent Result From E-Step Calibration

### ISSUE THREAD

**Issue by jormono** [teachingtechYT/teachingtechYT.github.io#137]
Hello,
I could be doing something wrong, following the tutorial/website step by step and I'm at the point of callibrating the E-Step value for my extruder. I ran the test and had about 15 mm remaining so I entered the suggested value from the calculator and did the test again to double check. The second time I had about 25 mm remaining. The Third Time, I had about 5 mm remaining.

I wound up resetting the value to the original which was 471.50

**Comment by teachingtechYT** [comment]
It's worth checking that the hobbed gear is free of filament debris and the grub screw holding it to the extruder stepper output shaft is tight.

If those are ok, it may be worth running the test in free air, as in the filament exits the extruder into free air instead of going into the hot end.

**Comment by teachingtechYT** [comment]
Closed pending an update from OP.
