### ISSUE TITLE
ender 6 se abl

### ISSUE THREAD

**Issue by bakaneko718** [teachingtechYT/teachingtechYT.github.io#138]
Not sure if anyone else ran into this yet or if im just doing this off a bit. The code from the drop down menu for g29 doesnt work with the ender 6 se. i guess since it's looking for a probe it thinks it crashes into the bed. is there another gcode for it?

**Comment by teachingtechYT** [comment]
I would suggest using the `M420 S1` option to restore a mesh you previously probed using the LCD controls.
