### ISSUE TITLE
Post-flow calibration g-code

### ISSUE THREAD

**Issue by Azariah98** [teachingtechYT/teachingtechYT.github.io#141]
I just finished calibrating flow, and I'm on to the retraction and temperature towers. Is there any way to take the flow percentage into account when generating the gcode for those? Since all of the flow settings are in the slicer, gcode from the web page won't know about any changes I need.

**Comment by teachingtechYT** [comment]
Please read the section at the bottom of the flow tab: Can I use this flow value in the other tests on this site?
You can't use a direct value which is explained there plus a work around if the flow rate is a long way out of spec.
