### ISSUE TITLE
Acceleration page feed rate

### ISSUE THREAD

**Issue by Atlas-Axe** [teachingtechYT/teachingtechYT.github.io#142]
In the acceleration page, when you start the feed rate test you have the users issue a G91, setting movement on all axes to relative. You never tell the user to issue a G90 after the test, which sets positioning back to absolute. There is the same item missing in the text associated with your video, although you do state it in the video.

While I caught it this time, I've missed it a couple of times in past, and the printer may slam into the limits if you submit a print job in that state.

**Comment by teachingtechYT** [comment]
Agreed, thanks for spotting. G90 instruction added to step 4.
