### ISSUE TITLE
Retraction test - too fast

### ISSUE THREAD

**Issue by bonoboxita** [teachingtechYT/teachingtechYT.github.io#144]
I've just tried the retraction test and the print speed is very high.
On my stock Ender 3 i was also suffering from significant underextrusion

**Comment by TownDrunk** [comment]
I'd like to see a input for speed, since I think it's too slow.
I get fantastic results with PLA or PETG on the retraction test, but had horrible stringing on the last PETG part I printed, using the settings from my retraction test.

**Comment by teachingtechYT** [comment]
Please use the controls on your printer to manually change the speed. I've never seen a printer that can't do this.
