### ISSUE TITLE
Can't find #define EXPERIMENTAL_SCURVE

### ISSUE THREAD

**Issue by AalianKhan** [teachingtechYT/teachingtechYT.github.io#147]
Hello I am new to 3D printing
I want to play with linear advance. In the docs, it says that you have to uncomment #define EXPERIMENTAL_SCURVE but I am unable to find it. I see  #define S_CURVE_ACCELERATION but I am not sure if its the same thing. Thanks

**Comment by Chron-O-John** [comment]
You should find it in Configuration_adv.h
In my File it is on line 1623
