### ISSUE TITLE
Slicer Flow Calibration – different thicknesses on walls of cube

### ISSUE THREAD

**Issue by drewnoakes** [teachingtechYT/teachingtechYT.github.io#148]
I performed the flow calibration test, printing the one-wall cube and measuring the thickness of each wall. Turns out they're all quite different! 

Any thoughts on what may cause this? Is this something others have noticed. If there's something to be said about this, it might make an interesting addition to the document. It also requires marking the axes before removing from the build plate, so that the orientation is not lost.

Thanks for this great site.

**Comment by ChrisToxz** [comment]
What is quite different? Anyway take a average of all sides to do calculation

**Comment by drewnoakes** [comment]
Average is easy to do but I think there is an underlying bias between the axes in my machine, perhaps the nozzle or the direction of travel.

From memory the numbers were .42, .48, .51, .55.

**Comment by ChrisToxz** [comment]
What machine btw? And did you print with default profile (except for the changes that are requested?, or did you use custom profile?

**Comment by drewnoakes** [comment]
CR-10S. Standard profile.

**Comment by teachingtechYT** [comment]
I have experienced this also. I don't have an explanation. However, I will add a note to the bottom of the tab.
