### ISSUE TITLE
Add leveling/distamnce print

### ISSUE THREAD

**Issue by rendez2k** [teachingtechYT/teachingtechYT.github.io#15]
Hi there, fantastic idea. One thing I always do is print 5 squares/circles on my bed to check leveling as per this: https://www.youtube.com/watch?v=RZRY6kunAvs&list=PLyelYMwIkPd4SlwcBTDj92t0eyGpvzIkB&index=2&t=196s

I find it an important step to double check leveling and distance is set correctly. The amount of newbies on FB group I've suggested this to, and its helped them proves its an important test print to run. Would be great if your tool could generate the test gcode.

**Comment by teachingtechYT** [comment]
I agree this would be a good thing to include. I usually use an 'X' but this would be easier to generate gcode for. It's still complicated as the entire gcode won't be moved together as the current generators do, but rather the five squares need to be positioned independent of each other in the right proportion. The delta version will be a mess too.
This will need time to get right.

**Comment by teachingtechYT** [comment]
This is now implemented, suits rectangular bed and delta bed with specified diameter. Full page with video snippets and refence images and diagrams.
Thanks to vector76 for their help.
