### ISSUE TITLE
Request to be able to select .6 nozzle.

### ISSUE THREAD

**Issue by mecra** [teachingtechYT/teachingtechYT.github.io#151]
It would be nice if the nozzle size can be changed. I've recently changed to .6 and I can't use any of these tests anymore. Thanks!

**Comment by 5teveO** [comment]
Or even common sizes - such as 0.8 and 1mm or smaller down to 0.2?

**Comment by wifiguru10** [comment]
Agreed +1

**Comment by TwoToneEddy** [comment]
This would be really handy!!

**Comment by iFrostizz** [comment]
I'm currently doing that on my Octoprint plugin, not too hard to change. You can contact me if you wanna beta test :)

**Comment by vcliment89** [comment]
Also would like this

**Comment by bderancourt** [comment]
Would like this too. Ideally, nozzle size and layer high should be configurable.

**Comment by Cosantoir** [comment]
I'm totally +1'ing this I've a volcano hot end id love to dial in and I dont have anything less than a 0.6 and would love to dial that in at least and anything else would be icing on a cake but adding a 0.8 and 1mm would be heaven

**Comment by johnkraczek** [comment]
+1 on this request as well.

**Comment by Glodigit** [comment]
+1 on this

**Comment by w0lv3r1nix** [comment]
+1, add 0.25 0.2 to that 🥇

**Comment by teachingtechYT** [comment]
Coming this week.
