### ISSUE TITLE
Flow calculation

### ISSUE THREAD

**Issue by ChrisToxz** [teachingtechYT/teachingtechYT.github.io#152]
See image. It says my new flow rate should be 91.42% 
I think a lot of people will think they will have to use 91.42%
But it is actually 92.42% of 114.29%

![image](https://user-images.githubusercontent.com/28065282/93686047-eec1f500-fab3-11ea-92cf-e97f75747888.png)

**Comment by GrealLakesGunpla** [comment]
No, the new flow rate is 91.43%.  If the measurements are correct, you need to reduce your flow 20%.
