### ISSUE TITLE
ESteps Calibration: M500 command does nothing on Prusa printers

### ISSUE THREAD

**Issue by Gei0r** [teachingtechYT/teachingtechYT.github.io#153]
Hi, could you add a note to the ESteps Calibration page that the `M500` command does *not* store the ESteps value in EEPROM on Prusa printers (see https://github.com/prusa3d/Prusa-Firmware/issues/21)?
Apparently you need to put the `M92` command into the GCode for every print.

**Comment by teachingtechYT** [comment]
Note added for update later this week.
