### ISSUE TITLE
Integrated gcode-sender

### ISSUE THREAD

**Issue by morrowsend** [teachingtechYT/teachingtechYT.github.io#154]
Great job on this site!

It'd be neat if there was a way to actually send the gcode directly from the pages instead of having to copy and paste them. For example, you could integrate [this google chrome plugin which does exactly that](https://github.com/sir-buckyball/chrome-gcode-sender).  For example:

- At the bottom of each page, there could be a button to send the gcode to the printer. 
- When a calibration value needs to be saved to the printer using an M command, a simple button on the page could allow this.
- A button next to each area that you're getting readings from the printer, such as Jerk that will send the command and then display the results to the user.
- Once someone has gone through the steps for calibrating a particular filament (retraction and linear advance) the settings could be stored as a setting on the user's computer using Chrome's history or a cookie and a new page could store buttons for these. For example, user inserts TPU in their machine, then opens this site and clicks the button "Sainsmart green TPU" which sends all the calibration for this from the last time they calibrated.

**Comment by teachingtechYT** [comment]
A nice idea but it adds a massive layer of complexity on top of an already frantic back end.
Remember that people have different printers, computers/phones and whatever else so something like this quickly becomes problematic with catering to everyone.
