### ISSUE TITLE
Add Z-probe offset calibration

### ISSUE THREAD

**Issue by Chuckame** [teachingtechYT/teachingtechYT.github.io#156]
Hello there,

Thanks for this very helpful calibration page!!

I think this is missing a z-probe offset tutorial to make it simple to adjust (when adding ABL, changing bed, etc...)
I found this great video (the one that really help me... the others are not fully comprehensible for me): https://www.youtube.com/watch?v=y_1Kg45APko

Here is the tutorial:

1. Launch auto home
2. M851 Z0 - Reset Z0Offset
3. M500 - Store setting to eeprom
4. M501 - Set active parameters
5. M503 - Display Active Parameters
6. G28 Z - Home Z Axis
7. G1 F60 Z0 - Move nozzle to true 0 offset
8. M211 S0 - Switch off soft endstops
9. Move nozzle towards bed slowly until the paper can barely move
10. Take note of the Z on the printer display (take that number and add the measurment of the calibration sheet or device used)
11. M851 ZX.XX (X.XX being your z offset achieved, can be negative)
12. M211 S1 - Enable Soft Endstops
13. M500 - Save settings to Eeprom
14. M501 - Set Active Parameters
15. M503 - display current settings

What do you think ?

**Comment by teachingtechYT** [comment]
I'm only reading this for the first time now, but in the interim I made a video about the subject which I have added to the page: https://youtu.be/fN_ndWvXGBQ
Thanks for the suggestion.
