### ISSUE TITLE
GCODE issues?

### ISSUE THREAD

**Issue by Cyanotic85** [teachingtechYT/teachingtechYT.github.io#157]
I've used gcode from this git pretty much since the start. I've never really had any issues. I got a Prusa the other day, and used the filament it came (the silver) with to run some stringing/temp tests. The tests came out terrible. I though maybe it was something with the gcode and my printer. I got a new gcode for my Ender and it came out bad as well. So, I tried different filament on my Ender and it's still coming out bad. I don't think it's anything that I'm doing since gcode from my slicer is still printing just fine.

Prusa on the left, Ender on the right.
![120141493_379152946415615_5741384345428856526_n](https://user-images.githubusercontent.com/66537541/94319865-92e6e880-ff59-11ea-93fa-9d20b76ad930.jpg)

Same artifacts are showing up on both printers, the pink filament had them as well, just harder to photograph.
![120197741_919065871953439_1070242311725919609_n](https://user-images.githubusercontent.com/66537541/94319864-924e5200-ff59-11ea-911f-77a81bd2b553.jpg)

This was the first thing I printed with the Prusa before I did any tests with the gcode from here. My Ender is still printing fine with other things as well.
![120257498_272611783742020_4199258485107057331_n](https://user-images.githubusercontent.com/66537541/94319867-92e6e880-ff59-11ea-8a8f-24e2329e2b6d.jpg)

**Comment by teachingtechYT** [comment]
I don't anything changed here to explain this. It is also an isolated report. I think we just put it down as an anomaly.
