### ISSUE TITLE
Extruder E-steps Calibration Page

### ISSUE THREAD

**Issue by WBugsbuny1** [teachingtechYT/teachingtechYT.github.io#160]
I have a Geeetech A10T. I have 3 filaments and one nozzle.
I ran the exercise on my first extruder and I got 19mm remaining and made the adjustments. Saved it and then ran the test again. Perfect.

Now I typed T1 to change tools to the second extruder and ran the test again. Now I have 27 mm remaining on my second extruder.

Can I correct my E-Steps for T0, T1, and T2?
Or do I have to find an average for my 3 extruders and deal with it with my slicer?

It would be great to include a note about dual extruders, or more, in the E-Step Calibration Page.

Great work on the Website!!!

**Comment by teachingtechYT** [comment]
Special note added to the bottom of the page in the next update. Thanks for the suggestion.
