### ISSUE TITLE
Suggestion: Do a home x and Y in GCODE before starting print

### ISSUE THREAD

**Issue by Mendingthings** [teachingtechYT/teachingtechYT.github.io#164]
On the first layer test, if you don't have the print head at x/y home and you start the print it will crash your print head.

**Comment by teachingtechYT** [comment]
Every test generated has a G28 to home. Therefore you should not need to manually home the machine first.
Could it be you put the printer in relative movement mode (G91) after another test and forgot to put it back in absolute (G90)?
