### ISSUE TITLE
VREF formula is wrong for my creality silent board

### ISSUE THREAD

**Issue by Zuckme** [teachingtechYT/teachingtechYT.github.io#168]
My creality silent board has R150 sense resistors not R100 so the VREF formula

TMC2208 - Legacy/standalone mode (as found in Creality silent boards)
VREF = (RMS current * 2.5) / 1.77

 is wrong, for details here:

[https://www.eevblog.com/forum/chat/3d-printer-yet/msg3271034/#msg3271034](url)

**Comment by teachingtechYT** [comment]
I've added your link and text to the site.
