### ISSUE TITLE
Acceleration Test EEPROM Settings

### ISSUE THREAD

**Issue by btwood** [teachingtechYT/teachingtechYT.github.io#169]
Somehow I accidentally overwrote my default settings with ridiculous values from the acceleration test gcode file.

I use ADVi3++ on Wanhao from Microcenter, so luckily it was easy to set them back, but because the default settings on my printer were the best, I decided not to set/reset anything.

Unfortunately my prints started looking terrible with a TON of ringing and ghosting. After some troubleshooting I saw that my acceleration settings in EEPROM were set to 9000, instead of 1000. The fix for this was to use pronterface, because you could use the LCD, but you'd be holding the button for 15 minutes trying to get it back down to something reasonable.

I don't know how my defaults got reset. Unfortunately I don't have a copy of the gcode, and the one I just generated doesn't have M500 in it.

Maybe add something to the end of the gcode to restore EEPROM settings?

Thanks for this great tool!

**Comment by teachingtechYT** [comment]
This is an interesting one. There is no way for the gcode to know what the previous values were before the test. I think adding an M501 to restore EEPROM values in end gcode of each of the tests should be ok. There might be other issues posting but we'll see.
