### ISSUE TITLE
Alternate first layer pattern

### ISSUE THREAD

**Issue by LordBBQ** [teachingtechYT/teachingtechYT.github.io#170]
This would work as follows:
1. Printer prints 20mm square
2. Printer raises z, and executes 'M0' (pause and wait for user).
3. User removes square, examines it. User presses continue (or clicks encoder knob) after examining.
4. Printer prints another square and repeats. User can readjust based on previous result

This would allow for more streamlined calibration

**Comment by teachingtechYT** [comment]
I respectfully disagree. The whole point of multiple squares to have a reference for multiple parts of the bed to test if it is level. Repeating squares in the same position or only a single square in one position negates this. I believe such a change would only confuse less experience users.
They concentrate on a single area, get it perfect and then wonder why the first layer is rubbish for other prints.
