### ISSUE TITLE
Misspelling on Slicer Flow Calibration Page

### ISSUE THREAD

**Issue by ericsnis** [teachingtechYT/teachingtechYT.github.io#171]
Super minor, just a misspelling
Toward the bottom of the page in the section labeled "Can I use this flow value in the other tests on this site?" The word javascript is misspelled as javacsript in the first sentence of the second paragraph.

It reads:

The short answer is: not really.

The gcode generators on this site work by using **javacsript** to modify source gcode originally created by Simplify3D. However, when you completed the calibration test above, you sliced your own gcode, making your own baseline and then making a flow adjustment relative to that. Therefore, this test is unique from the others on this site which is why the flow rate doesn't necessarily translate.

**Comment by teachingtechYT** [comment]
This one has been fixed, thank you.
