### ISSUE TITLE
On Retraction Tuning tab download Gcode button not produce gcode file.

### ISSUE THREAD

**Issue by pieterbritz** [teachingtechYT/teachingtechYT.github.io#172]
On clicking on the Download Gcode button, on the Retraction Tuning tab, produce a save dialog box with the option to save "retraction.sql" file, not a Gcode file.

**Comment by teachingtechYT** [comment]
I am unable to reproduce this and it is an isolated report. Furthermore, the site uses no sql files.
I'd suggest something funky happening on your end.
