### ISSUE TITLE
Extrusion direction is reversed. 

### ISSUE THREAD

**Issue by paravane** [teachingtechYT/teachingtechYT.github.io#173]
So when I slice using Cura my prints come out OK. If they were great I wouldn't be here calibrating my stuff in more.

But when I made my baseline cube it extruded the wrong direction. And just spit my filament out.

I have done the direct drive upgrade from Microswiss. But I haven't changed any wires and for all intents and purposes it extrudes the right way. Not sure why the Baseline GCode did it backwards and I'm not sure how to fix it.

Btw thanks for creating this site. This is awesome.

**Comment by teachingtechYT** [comment]
The direction of the extruder is handled by the firmware. There is nothing in this site that has the ability to override this.
Did you accidentally use an enormous retraction distance?
