### ISSUE TITLE
Acceleration Test: Inconsistent Z-Seam Location?

### ISSUE THREAD

**Issue by aleroy** [teachingtechYT/teachingtechYT.github.io#176]
During the acceleration test I noticed many layers start immediately before or immediately after the X or Y feature. For example:  layer 95 started just after the X feature, 96 started after the Y feature, 97 started before the Y, 98 before X, and 99 started at the front right corner. Most of the layers seem to start near the X feature. The few layers with neither feature start at the front-right corner. For a more accurate test, wouldn't it help to start every layer in the same corner?

With the print complete, I can hardly see any ringing/ghosting of the X or Y features throughout the entire range (300-800). Part of that may be because I printed in white. However, the notch on the diagonal side showed ringing/ghosting consistent with the example image in the "Interpreting Results" section.

I've attach the gcode it produced for me. I'm printing on a CR-6SE with 100 mm/s base feedrate. The range was 300 - 800 mm/s/s at 100 mm/s/s intervals.

[CAL_accel_300-800_100.gcode.zip](https://github.com/teachingtechYT/teachingtechYT.github.io/files/5454720/CAL_accel_300-800_100.gcode.zip)

**Comment by teachingtechYT** [comment]
Agreed and well spotted. For this test I'm going to set it to always be in a specific location:
![image](https://user-images.githubusercontent.com/8293825/125378479-23e85c80-e3d2-11eb-9124-c4489efaf537.png)
Thank very much. Will be included in the update later this week.
