### ISSUE TITLE
[Feature request] `G28 L;` start code for Lotmaxx SC-10 Shark ABL printer

### ISSUE THREAD

**Issue by SandorSzilard** [teachingtechYT/teachingtechYT.github.io#177]
It would be a good idea on the gcode generator to enter custom ABL code, or there should be `G28 L` in start code in the list.
Some printers are using this code for the BLTouch sensor ABL (ex. Lotmaxx SC-10 Shark).

**Comment by teachingtechYT** [comment]
This is already implemented. Please look at the custom start gcode section on every form. You should be able to add G28 L and it will execute immediately after the regular G28.
