### ISSUE TITLE
First Layer/Bed Level Clarification

### ISSUE THREAD

**Issue by TheAndr0id** [teachingtechYT/teachingtechYT.github.io#178]
This issue is very important to anyone who is still using manual bed levelling (Ender Series).  Yes it's not as sexy as retractions or acceleration settings, but still bread and butter... 

One of the things that I've always struggled with is how/where to level my bed with.  After finally sitting down and printing DOZENS of levelling patches I've come up withf a method that seems to be working.  I thought I'd pass on my findings so they might help others who are struggling as I was.  Maybe some of this could be incorporated into the First Layer/Bed Levelling page.

I've watched a half dozen videos of people shoving pieces of paper under nozzles and talking about "tension" without explaining what that actually means.  There are a bunch of things that need to be taken into consideration:

1. Paper thickness.  I've found variances (just in my home) from 0.06mm to 0.11mm.
    - If using paper make sure to check it's thickness, and confirm it's consistency.  I've had issues because I was getting different values from the same sheet of paper.  **DON'T TRUST PAPER**.
    - When using paper, find some that is at least 0.08mm thick.  Heavy printer paper should fall into this category.

2. Feeler Gauges
    - Watch out for the oil that these are packed in.  When cleaning, DON'T LET THEM SOAK, use dish detergent and clean and dry them quickly (or they will rust).  I'm not joking, 10 minutes in the soapy water destroyed almost all of my set.
    - Confirm their correctness as some of the ones I was using were wrong/mislabelled.
    - Don't "sweep" the gauge across the nozzle, put it between the nozzle and the bed and move it so the gauge stays between the two.
3. Tension between the bed and the nozzle
   -  The "magic" here is to find out that magic distance between the nozzle and the bed.  Some say this should be 0.1mm, some say 0.075mm.  I've found that around 0.09mm seems to work best for me.  I'll explain my method below.
   - Check the first layer pattern.  If using "rectilinear" or "zigzag" fill, look at where the fill switches direction and note the length of the "squish". 
   - Also if the first layer is too close the ridges may transfer up into the upper layers.  I was printing solid disks that were 2-3mm thick and the ridges in the first layer was causing a serious issue with the top layer of the disks.  (This was at a firm 0.08mm gap between the nozzle and the bed)
4. Uneven print surfaces.  Finding out your print surface is warped/bowed sucks.  Include some suggestions on how to fix it such as:
     - Painters tape (3M Blue seems to be the product of choice)
     - Tinfoil layers - tInfoil is between 0.016mm and 0.024mm depending on the type.  (I used cheap 0.016mm stuff)
     - Replace bed with mirror (has to be flat or the mirror goes all "wonky".
     - Flip the print surface over - this may change your first layer "texture".  (In my case the bow was only on one side - the textured one)  
5. Concentric nuts on the gantry.  These can come lose and cause the z gantry to "fall" ever so slightly.  Check their tension to make sure they are doing their job.

I gave up on using paper as it just wasn't consistent (and I buy good paper) so I picked up some feeler gauges.  After learning why they are packed in SO MUCH OIL, I decided to use the 0.08mm one for bed levelling.  Now reading how to use these things most of the stuff is for heavy duty mechanics and involves a hammer, I kind of had to run with it.   Here's what I've been doing:

1. Tighten the levelling knobs as far as they will go.  Don't crank them, but tight.   Then loosen 2 full turns.
2. Auto-home the nozzle and adjust the z-stop so the nozzle has less than a milometer of clearance.  **SLOWLY** move the nozzle around the bed adjusting all of the bed knobs so the nozzle clears the bed on all four corners
3. Heat the bed to your first layer temperature.  For myself this is 60C.  Also make sure your nozzle is clean of any  filament.
4.  Go back to the knob closest to the home location and raise/lower the bed until the gauge just loses touch with the nozzle.  This should be just over 0.08mm.  As mentioned above, make sure to not sweep the gauge side to side across the nozzle as the edges may "twist" up and give a false reading.  Keep the gauge under the nozzle and move it adjusting the height until the nozzle (vibration) goes away.

Now, I can't tell you exactly my nozzle height, but I can't get the 0.1mm feeler gauge under and the 0.08mm passes with no resistance so I'm guessing 0.09mm.  :)

Oh, and if you have a bowed glass plate like I had, putting a single layer of tinfoil over all the layers (picture kind of a pyramid of tinfoil sheets) hides all the tinfoil and gives a nice uniform look to the print bed hiding the "solution".

There.  I've given back and I feel better.  :D

**Comment by teachingtechYT** [comment]
Thanks for your input. It's impossible for me to put it into the video already embedded in that page. However, if you ever end up putting this on a standalone web page, reopen this wit the link and and I'll add it to the page.
