### ISSUE TITLE
Origin problem with FlashForge Creator Pro [waiting on feedback]

### ISSUE THREAD

**Issue by zhro** [teachingtechYT/teachingtechYT.github.io#179]
I have to use whpthomas's [GPX gcode to x3g converter](https://www.thingiverse.com/thing:81425) for this to print on my FlashForge Creator Pro. The problem I'm having is that the print is not centered on the build surface:

![image](https://user-images.githubusercontent.com/4738876/97775874-7d597580-1b3a-11eb-9f73-e507164f5182.png)

Here is the error I'm getting:

```
(line 17) warning G92 emulation unable to determine all coordinates to set via x3g:140 set extended position
current position defined as X:0.00 Y:0.00 Z:0.00 A:0.00 B:0.00
(line 17) warning G92 emulation unable to determine all coordinates to set via x3g:140 set extended position
current position defined as X:0.00 Y:0.00 Z:0.00 A:0.00 B:0.00
```

The extruder homes to the top-right corner before printing. Maybe this is related?

**Comment by teachingtechYT** [comment]
To fix this I need to know where 0,0 is on the printer's bed.
Based on your pic I would think it is in the middle of the bed. I would suggest ticking the appropriate box usually meant for deltas to see if that moves it.
This will introduce other problems so not a fix, just an information collecting step.

**Comment by teachingtechYT** [comment]
Stale
