### ISSUE TITLE
slicer flow calibration doesn't take into consideration horizontal expansion 

### ISSUE THREAD

**Issue by brainbukt** [teachingtechYT/teachingtechYT.github.io#18]
the slicer flow calibration test doesn't take into consideration horizontal expansion. the method shown for calibrating slicer flow doesn't take this into consideration and can lead to the issue you mention at the bottom of the page re under extrusion it maybe worth checking an tuning this to a degree before adjusting flow as this setting can also reduce elephants foot and bulged corners

**Comment by vector76** [comment]
What do you suggest as an improvement?  Perhaps multiple pillars with flat tops and adjustable choices for flow on each of the pillars, similar to the temperature test?

**Comment by brainbukt** [comment]
Horizontal expansion setting will actually automatically adjust flow to a degree and is specific to perimeters. It will correct hole sizes and elephants foot I would first tune this setting until foot is gone and then check flow.

**Comment by teachingtechYT** [comment]
This one needs a pull request with something concrete. Useful but I'm not sure it would the effort.
