### ISSUE TITLE
PIDTEMPBED echo:busy: paused for user

### ISSUE THREAD

**Issue by DavidDakus** [teachingtechYT/teachingtechYT.github.io#180]
Hi,

After running M303 E-1 S80 U1 on my Ender 5 Pronterface starts putting out these messages:

PID Autotune start
 bias: 86 d: 86 min: 79.02 max: 81.84
 bias: 83 d: 83 min: 78.86 max: 80.84
 bias: 81 d: 81 min: 78.89 max: 80.71 Ku: 113.19 Tu: 74.05
 Classic PID
 Kp: 67.92 Ki: 1.83 Kd: 628.69
 bias: 81 d: 81 min: 78.96 max: 80.71 Ku: 118.07 Tu: 74.06
 Classic PID
 Kp: 70.84 Ki: 1.91 Kd: 655.76
 bias: 81 d: 81 min: 79.05 max: 80.54 Ku: 139.12 Tu: 66.52
 Classic PID
 Kp: 83.47 Ki: 2.51 Kd: 694.04
PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
#define DEFAULT_bedKp 83.47
#define DEFAULT_bedKi 2.51
#define DEFAULT_bedKd 694.04
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
...

Can anyone help me with this problem..

I can't get my printer up to temp 240-80 for pet-g
PLA is not a problem..

**Comment by teachingtechYT** [comment]
You probably already have but look at what the LCD display is telling you.
This is not a problem related to this site, it has no place here.
