### ISSUE TITLE
Alternative terminal software via Google Chrome App

### ISSUE THREAD

**Issue by stdekart5827** [teachingtechYT/teachingtechYT.github.io#186]
I've had good luck using the following Google chrome App for sending and setting gcode for printers. Could be a good option for those with Chrome already installed regardless of computer OS:
https://github.com/sir-buckyball/chrome-gcode-sender

APP link:
https://chrome.google.com/webstore/detail/gcode-sender/ngncibnakmabjlfpadjagnbdjbhoelom?hl=en

**Comment by teachingtechYT** [comment]
Thanks for the suggestion. I have added a link to this on the tools tab of the troubleshooting page wit the other terminal software.
