### ISSUE TITLE
maximum acceleration set is wrong

### ISSUE THREAD

**Issue by nasone32** [teachingtechYT/teachingtechYT.github.io#189]
I have a delta printer, I noticed in the gcode
M201 X5000 Y5000 ; custom raise acceleration limits
this happens no matter what the maximum acceleration is set.

the code should chech the maximum acceleration set by the user and set "custom raise acceleration limits" accordingly.

thank you

**Comment by teachingtechYT** [comment]
M201 raised the absolute speed limit of the printer, but the actual print acceleration is set by the M204 commands that are inserted into the gcode.
Let's say you have a heavy moving bed. You might set the print acceleration with M204 to 1000 but limit this for the Y axis to 600 with M201.
I hope this makes sense. M201 and M204 work together and the generator works as intended. If M201 was not raised then the M204 commands would have no effect.
