### ISSUE TITLE
Documentation PID

### ISSUE THREAD

**Issue by FerretDave** [teachingtechYT/teachingtechYT.github.io#190]
on https://teachingtechyt.github.io/calibration.html#pid

You indicate in the video to run the M301 command manually to set the PID if M500 doesnt work (it doesnt appear to work on an Ender 3 v2), but you don't specify what command to use after running the test on the bed itself (M303 E-1 S60 U1).

So, can you update the webpage to show the M301 command detail (as per the video) and also to show what command is needed to set the values discovered from the M303 please.

**Comment by teachingtechYT** [comment]
Done.
