### ISSUE TITLE
Does Manual Mesh Bed Leveling Count As ABL?

### ISSUE THREAD

**Issue by ScottSpalding** [teachingtechYT/teachingtechYT.github.io#192]
For sake of example, I've flashed Marlin to my Mega Zero, enabled MBL, and then stored a mesh. I suspect that this counts as 'Restore Saved Mesh M420 S1'. However, when I see the prompt for 'ABL', I think, "I don't have a probe" and carry on. It may be worth clarifying whether or not MBL counts as ABL.

**Comment by teachingtechYT** [comment]
I guess it comes down to hoe each individual is using MBL but I would say the M420 option is typically correct. I've expanded the description to say ABL/manual.
