### ISSUE TITLE
Trying to use the various calibration tools for a snapmaker A350 and prints wont start. [more info required]

### ISSUE THREAD

**Issue by dlvence** [teachingtechYT/teachingtechYT.github.io#197]
Hello,
I am new to all this, and i went through and filled out the first layer test. i downloaded the Gcode and imported it into luban opened up the work space and tried to send it to the machinevia wifi, USB and by physically hitting the start button to run the Gcode provided. and every time the hotend nor the heated bed starts to heat up. any help would be appreciated. 
thank you. 
David.

**Comment by teachingtechYT** [comment]
Snapmaker uses Marlin so I can't see any reason the gcode won't run. Going to need more info to be able to do anything.

**Comment by teachingtechYT** [comment]
Stale
