### ISSUE TITLE
Possible extra UBL settings

### ISSUE THREAD

**Issue by nmw01223** [teachingtechYT/teachingtechYT.github.io#199]
Two extra parameters that could be considered:

1. Settable mesh to load (mine is typically in slot 0, not 1, some people may have more than one for different beds)
2. 3 point level check could be 'n' point level check - Marlin supports more than just 3 point

Other than that, pretty neat.

**Comment by teachingtechYT** [comment]
UBL is not very popular compared to other forms of ABL. Currently loading a mesh from slot one and then performing a three point tilt is supported. Building in additional inputs into the interface is going to confuse 99% of the people who use the site. The easiest workaround is to open the gcode and edit the start gcode to use a different slot.
