### ISSUE TITLE
Acceleration Tuning: Junction Deviation value not fine enough

### ISSUE THREAD

**Issue by SoulOfNoob** [teachingtechYT/teachingtechYT.github.io#201]
Hi, i just wantet to tune my acceleration and tried to type in my JD of `0.013` which is marlins default value <https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/Configuration.h>
but your form only allows values with two decimal places so i can't put in my actual number.

I don't know if this is significant but maybe other people run stock marlin as well and will run into this issue and get confused like me because i don't know enough about this value to confidently round it down.

**Comment by teachingtechYT** [comment]
Technically you can type in whatever number you want but this is an easy change so I've added an additional decimal place of accuracy to make using the field easier.
