### ISSUE TITLE
Flow calibration methodology is flawed

### ISSUE THREAD

**Issue by wildchron** [teachingtechYT/teachingtechYT.github.io#203]
Hi,

Thanks for the help with all calibration procedures. This is really awesome work.

You should however know that the flow calibration procedure proposed is highly dependent on the slicer.

1/ Assuming you are using CURA
CURA is basic in the way it models the flow: it considers the plastic deposit as a rectangular shape of width W by height H given by the parameters.
Obviously it is not the case as the borders will bee round but the good news is that is the rounded part will help the fuse between 2 adjacent paths. That is why, it is true that when you look at the GCODE, for a 0.4 width, the distance between the two paths will effectively be of 0.4.
If you do the math, you will find that, for 0.2 height and 0.4 width, you will get 0.44mm with a single wall / W + H*(1-Pi/4) (see in the link below the actual shape, we calculate the shape section to match the rectangular one Cura think it is).
So using your method with CURA, calibrating with one wall will get you extrusion rate that will make your print under extrude approximately by 10%.

2/ Assuming you are using PrusaSlicer
Prusa / Slic3r is smarter and assumes that the cross-section of an extrusion is a rectangle with semicircular ends.
See : https://help.prusa3d.com/en/article/layers-and-perimeters_1748
I will account for the rounded shape when calculating the width of a single wall. So, using the standard parameters of 0.45 width and 0.2 layer, if you print with one wall, you can expect to get 0.45 wall width. Using 0.4, you will get 0.4.
So using your method with PrusaSlicer, calibrating with one wall will get you accurate extrusion rate.

However, you should really use 2 walls to increase accuracy. One again, this is dependent on the slicer and the expected results are:
CURA with standard 0.4 walls, 0.2 height: 0.84
Prusa with standard 0.45 wall, 0.2 height: 0.86

Of course, for other slicer, one should dig the model they use.

**Comment by teachingtechYT** [comment]
Nice write up, thanks for taking the time.
Produce this to the average person and they will scratch their head.
Therefore, accounting for any minor inaccuracy is done with the last section of the page "Important note!"
The page suggests the user reply on what they see rather than any theoretical number and make final adjustments from there.
Perhaps the process could be more technically accurate but it is irrelevant. If a user follows the entire process they will arrive where they need to.
