### ISSUE TITLE
Nozzle size for temperature tuning gcode generator

### ISSUE THREAD

**Issue by Mrdindon** [teachingtechYT/teachingtechYT.github.io#207]
Would it be possible to add a nozzle size variable for the temperature tuning gcode generator ?
I tried it as is with a 0.6mm nozzle and I think it didn't work because the code is probably calibrated for 0.4mm nozzle right ?

**Comment by zsolt320i** [comment]
i opened the same issue but for all the tests not just for temp tower.
supporting

**Comment by NickdeK** [comment]
Duplicate of #195

**Comment by teachingtechYT** [comment]
Duplicate but this on coming later this week.
