### ISSUE TITLE
Needs more customization settings

### ISSUE THREAD

**Issue by eblieb** [teachingtechYT/teachingtechYT.github.io#209]
I realized after running some of these tests that they actually aren't doing what I needed them to do.
Specifically
for PETG retraction and temperature testing, the fan options needs to be able to be 5% fan after layer 2. 
Also there is no setting for Flow %. I calibrate my Esteps and then use flow % to fine tune each filament to the proper value. This allows me to change out filaments and not have to constantly recalibrate my e-steps. 

Really like these tests, but without a little more ability to modify them, it isn't that useful

**Comment by teachingtechYT** [comment]
Firstly, if you think this *free* site is not useful then there is nothing forcing you to use it.
Secondly, there are already instructions for altering flow with the custom start gcode. There are explanations there and on the flow page. Please read them.
The last request about the fan speed having more control is a good one, and is being introduced later this week.
