### ISSUE TITLE
improve calibration for TPU

### ISSUE THREAD

**Issue by lukesandidge** [teachingtechYT/teachingtechYT.github.io#211]
It would be handy to have print speed and no infill  controls to enable tuning for TPU.

**Comment by teachingtechYT** [comment]
Print speed can be controlled from your printer.
As for infill, I can't see how this would affect tuning things like retraction, temperature, etc. Yes, the print will be less flexible with more infill but that shouldn't matter for these tests as you will use the infill you want when you carry the settings over to your normal printing. Unless there is something I'm missing?
