### ISSUE TITLE
baseline print never fully prints top layer 

### ISSUE THREAD

**Issue by capposteve** [teachingtechYT/teachingtechYT.github.io#213]
on my ender 3 v2. i have tried this 4 times, and never prints the top layer. its set up coreectly as per instructions, calibrated correctly, e steps calibrated but no matter what i do it never prints correctly. all other faces are perfect. just the top later. any ideas?

**Comment by teachingtechYT** [comment]
I would suggest previewing the gcode in your slicer as per the instructions. This will tell you if the file has somehow been truncated.
For me to assist you further you need to supply a pic of this preview plus a pic of your print.
