### ISSUE TITLE
Add Skirt to g-code files

### ISSUE THREAD

**Issue by lwsmiser** [teachingtechYT/teachingtechYT.github.io#215]
When printing your calibration box for Acceleration and Jerk the first layer frame does not start printing until 1/3 the way through the first line.  Adding a skirt should prevent this shortcoming of your g-code output.  Unless there is another way of adding it short of editing the file I request this change.

**Comment by teachingtechYT** [comment]
When I started the site, I put in place a constraint that each print should fit within a 100 x 100 mm bed. For an update at the end of this week, I have upped that to 120 x 120 mm, and changed the accel test tower to not have a solid base but instead to print a 5 perimeter wide brim. This was implemented to speed up the overall print time.
All of this aside, the real question is: Did the print complete successfully and were you able to tune your acceleration, etc? If so, it is very unfair to use the term 'shortcoming'.
