### ISSUE TITLE
maximum feedrate test understated

### ISSUE THREAD

**Issue by TownDrunk** [teachingtechYT/teachingtechYT.github.io#216]
I was wondering why I had under-extrusion at .3mm at 150mm/s until I did this so-called "optional" test.

Based on my testing, a feed rate of 200 seemed to be my max and that helped me out a LOT. Then today I noticed that .3mm layer height, which I use a lot, was much worse than .2mm.

I think this test is understated and it shouldn't be optional at all. It can cure a lot of under-extrusion problems.

**Comment by teachingtechYT** [comment]
I agree with you. I can never force anyone to do any of these tests but I have added the phrase 'strongly recommend' to the title.
