### ISSUE TITLE
Request - Record generator settings in comments at start of site generated gcode.

### ISSUE THREAD

**Issue by madpenguin0515** [teachingtechYT/teachingtechYT.github.io#217]
It would be nice to record any settings used to generate code (ie retration tower settings used) in a header comment in the .gcode file.  That way this could be referenced later.

**Comment by teachingtechYT** [comment]
There is already a feature on this site that does this. Not in the header but instead in a text file. Try the "output settings summary" button on each form.
I prefer to keep the actual gcode as clean as possible.
