### ISSUE TITLE
accelerationsettings.txt bugg

### ISSUE THREAD

**Issue by kdkwarhead** [teachingtechYT/teachingtechYT.github.io#221]
https://teachingtechyt.github.io/calibration.html#accel
Gcode is correct in ”acceleration.gcode”.

**Accel for layer A is always identical to Layer F** in ”accelerationsettings.txt”

Segment | M204 P Acceleration |  M205 Jerk X  |  M205 Jerk Y   
   F    |    3000 mm/sec/sec   |     8 mm      |     8 mm (correct)
   E    |    2500 mm/sec/sec   |     8 mm      |     8 mm (correct)
   D    |    2000 mm/sec/sec   |     8 mm      |     8 mm (correct)
   C    |    1500 mm/sec/sec   |     8 mm      |     8 mm (correct)
   B    |    1000 mm/sec/sec   |     8 mm      |     8 mm (correct)
   A    |    **3000** mm/sec/sec   |     8 mm      |     8 mm (**was set to 500 on home page**)

Also, a brim on the outside and inside instead of a complete floor would be nice since my ABS wants to lift the corners.

**Comment by teachingtechYT** [comment]
Fixed the highlighted bug, and found another. Y jerk reported as X jerk.
Will appear in an update later this week.
That update also happens to include a change in brim vs solid first layer on that test to speed it up.
