### ISSUE TITLE
temperature tuning on ender 3 v2

### ISSUE THREAD

**Issue by capposteve** [teachingtechYT/teachingtechYT.github.io#224]
as above. this does not work correctly, or should i say the gcode does not when using it with cura. when it does the initial layer it dumps filament in the corners of the skirt, twice. then does the same thing on the actual layer of the test piece. leaving a huge blob which then causes the nozzle to ride up over the blob putting the bed out of level

**Comment by teachingtechYT** [comment]
I'm sorry but you are fundamentally misunderstanding the site.
You are not meant to use Cura. The whole point of these forms is to generate gcode to be directly printed by the printer, not go into Cura.
Also, you are the only person to ever report this as an issue which suggests it is working perfectly for everyone else.
My apologies if I have misunderstood the problem.
