### ISSUE TITLE
Stepper Motor Current Tuning

### ISSUE THREAD

**Issue by Daddyguitar** [teachingtechYT/teachingtechYT.github.io#225]
Hi Everybody!
I decided to submit this "issue" because I'm losing my mind on this topic...

First thing. I just need to set the stepper motor current because I've changed the stepper driver on my Anycubic i3 Mega S.
I don't want to change the whole firmware but just set the correct current. Untill now I've done everything with Pronterface, but now it looks like I have to download one software, with another software and another software just to change the current?
You probably would say "no, you just need the M906 and set whatever you want." Ok. But how can be possible that exist a command to change the stepper motor current but there is not a comman to just check the current setting right know?
Do I really need  to install all that stuff just to know which mA is set right know? I don't want to change it without knowing the previous value if I will ever need to reset that value.

And even more important, I've changed all my 5 stepper driver with the TMC 2208 V2  which are for X,Y,Z and the extruder, BUT, following the guide I know that if I check the configuration_adv.h i will find a mA current value for X,X2,Y,Y2,Z,Z2,Z3,Z4,E0....E7. Am I supposed to change the curren value on every single one of this current settings? 

An what these example on Marlin web site means?
"Set the XYZ motor currents to 5mA:
M906 X5 Y5 Z5
Set the E1 motor current to 10mA:
M906 T1 E10
Set the X2 motor current to 5mA:
M906 I1 X5"

Why "M906 X5 Y5 Z5" is straight foreward ad to change E1 I have to use T1 and for X2 I1???

Thank you and sorry for my  noobiness.

**Comment by teachingtechYT** [comment]
This is not the place to post technical support unrelated to the site.
