### ISSUE TITLE
Would be nice to add how to determine if you have linear advance enabled on your firmware (and which version).

### ISSUE THREAD

**Issue by dstrohl** [teachingtechYT/teachingtechYT.github.io#229]
,,

**Comment by teachingtechYT** [comment]
If linear advance is enabled, the LCD configuration menu will have an entry for linear advance. As for the version, that is trickier, but can be deduced.
The value already stored with be much smaller for V1.5 vs V1.
"Consider a Start value for K of around 0.1 up to an End Value for K of around 2.0 for LIN_ADVANCE v1.5 or around 30 up to an End Value for K of around 130 for v1.0."
https://marlinfw.org/docs/features/lin_advance.html
