### ISSUE TITLE
set both bed and hotend temperatures then home before waiting for temps

### ISSUE THREAD

**Issue by Spartan-II-117** [teachingtechYT/teachingtechYT.github.io#233]
M140 S60 ; custom bed temp
    M104 S205 T0 ; custom hot end temp
    G28 ; home all axes
    M190 S60 ; custom bed temp
    M109 S205 T0 ; custom hot end temp
this ensures that you do not have a hot end sitting on the bed while it heats.

bonus, draw an intro line like the Prusa slicer to make sure the filament is ready.

**Comment by teachingtechYT** [comment]
A small quality of life improvement sure, but not necessarily suitable for all printers. The second request is another example of this, as any priming sequence that works well on a Cartesian will be a disaster on a Delta. Therefore, please insert your prime sequence into the custom start gcode section as instructed.
