### ISSUE TITLE
Gcode Downloads as .txt

### ISSUE THREAD

**Issue by RSquared83** [teachingtechYT/teachingtechYT.github.io#236]
When I click on any of the Download Gcode buttons the file downloads as a .txt file and it will not run on my 3D printer. How do I get the file to download as a .gcode file so I can read it on my 3D printer?

**Comment by dan-and** [comment]
I always get the downloads as .gcode files. 

What Operating System and Browser are you using?

**Comment by RSquared83** [comment]
Windows 10 and Firefox. I will try a different browser. Thanks

**Comment by teachingtechYT** [comment]
First I've heard of this, hopefully you found the problem.
