### ISSUE TITLE
Please add how to calibrate dual Z screws

### ISSUE THREAD

**Issue by theschles** [teachingtechYT/teachingtechYT.github.io#237]
Hi there,

Thank you for such a great tutorial of the Ender 3. I have a Sovol SV01 with dual Z screws connected to separate stepper motors -- but driven by a single stepper driver on the mainboard -- so Marlin's G34 command is not an option unless I change system boards (I didn't realize this when I bought the Sovol's "silent board" add-on).  The closest I've gotten is [this video from myfordboy](https://youtu.be/ilezW1FQ_JU?t=163) where he does some measurements and adjustments to align everything. 

UPDATE 2021-01-19: I just found [this video](https://www.youtube.com/watch?v=MNIYfNr9g1I) with blocks that one prints and then one adjusts the Z screws so that the X-gantry is level with the base

Would you please consider adding a section and video specifically for calibrating dual Z screws -- both:

1. with a single driver, and
2. with multiple drivers (with which I'm assuming one can do the G34 command)

(PS I added this originally as a comment on the assembly video, then found the Github repo...so since this is probably a better place for this request, I deleted that video comment.  I hope that's ok)

**Comment by teachingtechYT** [comment]
Only reading this now but hopefully you saw this one when it was released: https://youtu.be/6UgT9YqY3UA

**Comment by Homer-S** [comment]
Hi!

I had a question about that video, specifically G34. Assuming you are on a printer without a fixed bed, doesn't G34 for calibrating a dual z-axis with dual drivers align the gantry to a moving bed that itself is trammed using the z-axis? I would expect for the bed tram to be accurate the z-axis gantry would have to be trammed to something fixed, either the upper frame or the lower frame of the printer.

Homer
