### ISSUE TITLE
Retraction Test Final Homing needs to be for all axes on Delta. [awaiting feedback]

### ISSUE THREAD

**Issue by rlatimer4** [teachingtechYT/teachingtechYT.github.io#239]
After the print has finished for the Retraction test, G28 X0 is called, which doesn't work for delta printers.  This needs to just be G28 for deltas.  

Also as a reminder Issue #196 and Issue #165, are still open for Deltas.

**Comment by teachingtechYT** [comment]
This one is tricky, as G28 on the end will destroy the print and or printer on anything besides a delta.
I've just added support for custom end gcode (released end of the week), so if you could add a G28 there to run after G28 X, does that solve the problem or is the G28 X dangerous for the printer?

**Comment by teachingtechYT** [comment]
Added a button for a regular G28 for deltas.
