### ISSUE TITLE
Retraction test fail on delta printers

### ISSUE THREAD

**Issue by lucaslsk** [teachingtechYT/teachingtechYT.github.io#242]
after homing, the movement of z axis should be done before xy. Move xy before z will cause motor shift by crash on end stopper.

**Comment by ddacunha** [comment]
I confirm this and created the [pull request 301](https://github.com/teachingtechYT/teachingtechYT.github.io/pull/301) to fix this issue.

**Comment by teachingtechYT** [comment]
This is fixed in an update later this week.
