### ISSUE TITLE
Fan never turns on in temp tuning with FLSun QQS

### ISSUE THREAD

**Issue by jakebullet** [teachingtechYT/teachingtechYT.github.io#245]
FFLsun QQS Delta, Repieter firmware.
Trying PETG so fan is set to off and noticed then when it is doing the bridge the fan never turns on. 

Should come on 100% on bridging.

**Comment by teachingtechYT** [comment]
This was a bug with the original slicing and should be fixed in an update later this week. Thanks for posting.
