### ISSUE TITLE
Flexbox for navbar

### ISSUE THREAD

**Issue by stephen304** [teachingtechYT/teachingtechYT.github.io#25]
Currently the navbar overflows with tabs and looks kinda messy. In order to make the tabs fill the width, I suggest setting display:flex on the container and increasing the mobile navbar breakpoint to 1080px.

Before:
![image](https://user-images.githubusercontent.com/981915/90322912-2aebbe00-df28-11ea-93dc-a2114c6e098e.png)

After:
![image](https://user-images.githubusercontent.com/981915/90322907-13acd080-df28-11ea-9853-fef185148f53.png)

If more stuff needs to get added later, then maybe sorting the pages into dropdown categories would be better.

**Comment by lmckeen** [comment]
https://github.com/teachingtechYT/teachingtechYT.github.io/pull/36

my PR should resolve this issue

**Comment by teachingtechYT** [comment]
This one is a matter of personal preference, and my taste prefers the original design. I do appreciate you talking the time to do the pull request.

**Comment by lmckeen** [comment]
sorry @teachingtechYT , the PR for this does not use the new look, but the old one just using flexbox and responsive design, and actually goes much more in to depth with fixing performance issues and a design that works on mobile devices

for desktop devices
before
![image](https://user-images.githubusercontent.com/11928027/90348019-44653680-e00a-11ea-8f86-370ce94a95ed.png)

after
![image](https://user-images.githubusercontent.com/11928027/90348097-9b6b0b80-e00a-11ea-934b-2811ef7c9952.png)


and for mobile devices
before
![image](https://user-images.githubusercontent.com/11928027/90348120-c35a6f00-e00a-11ea-80a1-df9332761fdc.png)

after
![image](https://user-images.githubusercontent.com/11928027/90348153-f3097700-e00a-11ea-996a-d3d674eca55c.png)
![image](https://user-images.githubusercontent.com/11928027/90348171-09173780-e00b-11ea-80e7-87b40e1c0d05.png)
