### ISSUE TITLE
Z-Hop

### ISSUE THREAD

**Issue by bipsendk** [teachingtechYT/teachingtechYT.github.io#250]
When running the temperature tower test, Z-Zhop is enabled

What is the value ? Can it be disabled ?

**Comment by gabba-the-hutt** [comment]
this issue isn't fixed yet right?
my printer doesn't like z hop so he f**ks up this test all the time

**Comment by teachingtechYT** [comment]
Full control over z hop in all tests will be available in a major update later this week.
