### ISSUE TITLE
More info on how to do this without Pronterface or Octoprint.

### ISSUE THREAD

**Issue by mkdfrvr** [teachingtechYT/teachingtechYT.github.io#254]
Fantastic resource! Please add more info on how to do these calibrations without Pronterface or Octoprint if possible. Many of us first-timers trying to set up our first printers don't have access to Pronterface or Octoprint. Need to have more information on how to do this from the onboard printer menus and display.

**Comment by wa-114** [comment]
That's exactly the problem I'm facing. I'm just not sure how to proceed. Do you know a way to do this by using an sd card?

**Comment by teachingtechYT** [comment]
Instructions for setting up Pronterface are now on the troubleshooting page. I'll add a note to point to this n the relevant pages.
