### ISSUE TITLE
Retractions

### ISSUE THREAD

**Issue by nolosep** [teachingtechYT/teachingtechYT.github.io#256]
Good afternoon

I have done the retraction test and perfect.

As the data is transferred to the laminator, the retractions return.

Can you tell me the speed, flow and acceleration of the GENERATED GCODE?

**Comment by teachingtechYT** [comment]
The site is soon to be updated with full access to the slicing profile. In the meantime:
Base feedrate of 60mm/sec, 50% for perimeters, 80% for solid infill, 50% first layer.
Flow in simplify3d profile is 0.9.
Acceleration is not changed in the gcode generated so whatever is used by your firmware.
