### ISSUE TITLE
Suggested Value Increments for Iterative Tests

### ISSUE THREAD

**Issue by Ralnarene** [teachingtechYT/teachingtechYT.github.io#257]
The iterative tests (the ones where you first vary one parameter, then the next, etc) don't have suggested values to iterate by.  Could you include notes with suggested ranges to vary them by?  In some it's not clear at first glance whether the user should be changing the number by any set interval.  Should they go positive or negative?  Should they be iterated by .1, 1, 5, 10, 50, 100, etc?

It would just be helpful to know for stuff like the accceleration test where it's not clear what the user should be incrementing by in the jerk settings.

**Comment by teachingtechYT** [comment]
Agreed. Adding this to the next update at the end of the week. Thanks for suggesting.
