### ISSUE TITLE
New Feature Request - outer wall speed test tower [Accepted and upcoming]

### ISSUE THREAD

**Issue by midicdj1000** [teachingtechYT/teachingtechYT.github.io#258]
I notice while calibrating my anycubin chiron it has noise in the outer walls and I can tweak based on the print speeds. It would be very useful to generate a tower with changing print speeds so you can fine tune for quality.
![EnCJbCWXEAAUly3](https://user-images.githubusercontent.com/30492351/107849697-f7b1bb00-6df4-11eb-9478-64de90c9afde.jpg)

one example of changing the print speed

**Comment by Gitdad** [comment]
I second this. It would be great to get a speed option added to the acceleration / jerk test. 

p.s. great work on the site!

**Comment by teachingtechYT** [comment]
I will keep this in mind for a future test. I don't think it would be too hard to implement.

**Comment by teachingtechYT** [comment]
I designed the CAD for this yesterday and implemented an early, manual version to torture two extruders with flexible filament.
Here is the geometry:
![image](https://user-images.githubusercontent.com/8293825/140217150-059ea8b1-d190-4aa5-a008-3cfcb45fe8ba.png)
The aim to provide a range of shapes, while still being quick to print.
The user will set their slowest feedrate the lowest segment, then the target feedrate for the next four segments. The STL will be sliced in vase mode and use simple M220 commands to set feedrate percentage. This is the reason for vase mode, to avoid retractions also being sped up with M220.
The test worked well in my testing thus far. The single outer wall shows extrusion quality nicely on the largest curved side, and the fine details are good for exposing a lack of flow rate when things speed up.
Feedback welcome.

**Comment by teachingtechYT** [comment]
Implemented!

**Comment by midicdj1000** [comment]
I just ran this on my chiron and it is exactly what I wanted.  Thank you so much
