### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by HaseHinz** [teachingtechYT/teachingtechYT.github.io#264]
Hello,

I noticed a spelling error on the Teaching Tech website. In the "Contact" category, the first bullet point says:
"I don’t offer personal technical support, paid or otherwise, to the general public, _Patrons_, anyone. Please do send such requests, you will not receive a reply."

Shouldn't it be, "I don’t offer personal technical support, paid or otherwise, to the general public, **Patreons**, anyone. Please do send such requests, you will not receive a reply."?

Best regards

**Comment by teachingtechYT** [comment]
Patreon is the website/service, and the supporters who use it are patrons. That's at least how I understand it. Thanks for the consideration.
