### ISSUE TITLE
Slicer Flow Calibration: Flow and Initial Flow

### ISSUE THREAD

**Issue by GeodeLX** [teachingtechYT/teachingtechYT.github.io#265]
This is a minor change: On the Slicer Flow Calibration page, you mention setting the "Flow" value for Cura, but I didn't see "Initial Flow" mentioned.  I would encourage you to add a note that tells Cura users to set both "Flow" and "Initial Flow".  Took me a while to figure out why my first layer was so globby!  :-)

**Comment by teachingtechYT** [comment]
Added, thank you.
