### ISSUE TITLE
Feature Request: Supports Calibration

### ISSUE THREAD

**Issue by DragonGyld** [teachingtechYT/teachingtechYT.github.io#268]
Lots of people try and use supports for prints, but if the settings aren't right then you tend to get sagging of the layer lines on the first layer between the model and support interface. I suggest adding a section for supports that help the user figure out the best support settings for them by adjusting certain settings one at a time like retraction. Also the test model should have an angled overhand as well as perfect 90 degree overhang, then there will be testing for both types of overhangs. Also it should be made that the user can set the layer height to whatever height they want to use, so if someone wants to test for 0.12mm layer height or someone else wants to use 0.2mm or 0.08mm, make it changeable.

It would also be great to make it possible that the user can select the slicer they use, it has been proven that there is print quality differences between S3D, Cura, and Prusa slicer. So if the user could select the slicer they use and then the code generated was originally created from that slicer then it would be like using what you are used to and the output you get is what you would get using your slicer of choice. I know from experience this is very true because I have used the retraction tuning section on the calibration site and received good results, but the code from the calibration site is generated from S3D. I then proceeded to use the results I had received in Cura because I do not own S3D and the stringing on the print was worse then what I had with my old settings in Cura

**Comment by teachingtechYT** [comment]
Unfortunately this is slicer specific, so there is not a test my site can offer to suit because the gcode originally comes from Simplify3D.
You have a long list of requests but you need to understand there are technical limitations to what can be achieved from a free, open source gcode tweaker online.
