### ISSUE TITLE
Filament flow between test segments

### ISSUE THREAD

**Issue by marcinzp** [teachingtechYT/teachingtechYT.github.io#269]
Hello, while running "Acceleration Tuning" test (and tuning high speed printing [300-400mm/s + acceleration 3000] + Volcano-like extruder on Ender 5) I've noticed, that between test segments, at the end of the Y wall, there's a repetitive place, where printing stops for c.a. 0.5 second, changes Z position few milimeters down and up, and then continues the print. While there's no filament retraction at this moment, a bit of the filament flows and makes a "blob" in the corner. I don't have this effect in slower test prints.

**Comment by teachingtechYT** [comment]
This test is being rejigged (out later this week) with two changes relevant to your query:
1. Z hop will be completely controllable by the user.
2. The start and end points of each layer are no longer random but in a strategic part of the print.
Hopefully this fixes your problem.
