### ISSUE TITLE
Harness Calibration Shape Generator Tools

### ISSUE THREAD

**Issue by pandaero** [teachingtechYT/teachingtechYT.github.io#273]
There is a Cura extension that creates calibration shapes, as well as provides G-code scripts to change temperature etc. I find this is easier as the generated gcode from the site has given me problems (Ender 3 V2).

[Cura plugin site](https://github.com/5axes/Calibration-Shapes/wiki)

Could we add a section in the calibration page for own-gcode generation using this tool?

**Comment by teachingtechYT** [comment]
So you want me to add a section to the site telling people not to use the site?
I'm sure the plugin, like this site, ha strengths and weaknesses. I;m sure you can understand I'm not going to spend time and energy documenting the plugin here when I could be improving this site instead.
