### ISSUE TITLE
Gcode file cannot print using Octoprint

### ISSUE THREAD

**Issue by Nuttavoot** [teachingtechYT/teachingtechYT.github.io#279]
The created "First layer" gcode file was successfully loaded to Octoprint but when load or press print button, nothing happended, no load, no print.

See attached file created. Also try with Octoprint in safe mode with same result.

Edited: This file printed normally when put into sdcard then print.

[firstlayer.zip](https://github.com/teachingtechYT/teachingtechYT.github.io/files/6175148/firstlayer.zip)

**Comment by teachingtechYT** [comment]
I can't see anything in the file that Octoprint wouldn't like. In fact this the first report of compatibility problems I've had.
I'm happy to look into it but you will need to provide a lot more information.
Octoprint will likely have given some feedback in the terminal and if not, the logs. If you can fish this out I will have a chance.
