### ISSUE TITLE
SnapMaker Original: Retraction test crashes hot end (solved)

### ISSUE THREAD

**Issue by dbreggin** [teachingtechYT/teachingtechYT.github.io#282]
The Snapmaker Original 'Home' position has the hot end **below** the surface of the bed.  Running the G-code as generated for the Retraction test crashed it into the bed.

After comparing the G-code from the Temperature test (which executed flawlessly), I discovered the fix is to insert this line between line 21 and line 22 of the Retraction test code:      

`G1 Z0.400 F1200`

This raises the hot end **above** the bed level before moving to the starting X/Y coordinates.

**Comment by teachingtechYT** [comment]
If the printer is following the gcode then the nozzle should be above the bed by 0.4mm and move freely. Perhaps a strange value was used for z hop in the retraction test?
Either way, all of the tests are being refined this week in regards to z hop so hopefully the new version works for you without alteration.
