### ISSUE TITLE
[BL-Touch Troubleshooting Addition] Marlin Hotend_Timeout - BL-Touch

### ISSUE THREAD

**Issue by chiral-lab** [teachingtechYT/teachingtechYT.github.io#285]
Hi,

I have read and used your fantastic guide for the BL-Touch Sensors and I had some issues when I increased the number of grid points, which you might want to add to your troubleshooting page to save someone else the hassle I had in finding a soultion.

Right after the probing my hotend and bed powered down. I had to search for a while but in the end I found that Marlin has a feature called "HOTEND_IDLE_TIMEOUT" which I had activated. Unfortunately the standard value in Marlin for the deactivation is set to 5 minutes and the probing was taking long enough to trigger the timeout thus driving my printer into the cold extrusion prevention.

best regards
Chiral

**Comment by teachingtechYT** [comment]
Hi Chiral,
thanks for the tip. I have added it to the BLtouch troubleshooting page, quoting and crediting you.
