### ISSUE TITLE
[BL-Touch Troubleshooting Addition]  Online bed mesh visualizer 

### ISSUE THREAD

**Issue by ouartsiw** [teachingtechYT/teachingtechYT.github.io#286]
Hello,

I personally don´t have Octoprint available, but i wanted to visualize my bed mesh data, so i stumbled across this [website](http://lokspace.eu/3d-printer-auto-bed-leveling-mesh-visualizer/). 
It uses the same techniques as the Octoprint plugin to plot the bed data.

May be you can add it to the troubleshooting BL Touch / ABL section. It can be helpful for some people i think.

Thank you for this awesome work !

Cheers

**Comment by teachingtechYT** [comment]
Thank you, great resource. Now linked with the Octoprint version on the same page.
