### ISSUE TITLE
Acceleration Tuning - only numbers ending with 10

### ISSUE THREAD

**Issue by jordiman1991** [teachingtechYT/teachingtechYT.github.io#288]
Hello,
I'm following all of the calibration/tuning tabs. I noticed during the Acceleration Tuning that I'm only allowed to use numbers ending with ten (10). So for example A = 310, B = 410. If I want to choose 300 for example, it will highlight the entry box with a red border stating the input is not allowed.

![afbeelding](https://user-images.githubusercontent.com/6206205/113365723-5dcbb080-9357-11eb-8896-beae638afea0.png)

**Comment by teachingtechYT** [comment]
That's a strange one. Here is how each field is defined:
![image](https://user-images.githubusercontent.com/8293825/125440032-5ce8fe23-78ad-420d-ba6f-3bcdd34d7c16.png)
There shouldn't be anything that prevents the numbers you want. I'm updating the site this week and I'll change the increment to 10 from 100. In the meantime, the form should still submit and process despite the browser showing the field as red.
