### ISSUE TITLE
First Layer: Incorrect label for ABL

### ISSUE THREAD

**Issue by khosrua** [teachingtechYT/teachingtechYT.github.io#289]
The option for Prusa mk3 is labelled as G28 then M80, instead of G80. The code is correctly generated as G80

**Comment by IBNobody** [comment]
Ran into this as well.

![image](https://user-images.githubusercontent.com/5863888/114295553-92ccb700-9a6b-11eb-978f-ee606090f14b.png)

**Comment by teachingtechYT** [comment]
Fixed, thanks.
