### ISSUE TITLE
Retraction test using ABS heats not getting to temp.  

### ISSUE THREAD

**Issue by MJHirsch1** [teachingtechYT/teachingtechYT.github.io#290]
I just tried to run the retraction test.   The test did not heat up enough to melt the ABS.

Looking at the code, it had
M140 S100 ; custom bed temp
M190 S100 ; custom bed temp
M104 S250 T0 ; custom hot end temp
M109 S250 T0 ; custom hot end temp

I replaced it with this from a cura code that works and the print worked.
M140 S95
M105
M190 S95
M104 S240
M105
M109 S240

Not sure what the T0 is but it seems to be an issue for me using an Ender3pro with a SKR mini v2 with newer nightly firmware from Marlin.

**Comment by teachingtechYT** [comment]
T0 selects hot end 1. Some firmwares have a problem if this is not specified.
This box is on every generator, please use it to get around you problem.
![image](https://user-images.githubusercontent.com/8293825/125440918-872999c4-6f49-45b8-8cea-9b85dc821f85.png)
