### ISSUE TITLE
New feature : retractation test

### ISSUE THREAD

**Issue by bilame** [teachingtechYT/teachingtechYT.github.io#291]
Hello everyone,
the print with the gcode from the webpage didn't stick to the bed until i figured out the slot was 1 instead of 0 (mine).
It should be great to be able to choose the slot for the UBL or at least to specify that it is slot 1 in the gcode.
Thanks,
Bruno

**Comment by teachingtechYT** [comment]
Duplicate of #199 
Please see my response there.
