### ISSUE TITLE
First layer: additional info for V rollers and ABL

### ISSUE THREAD

**Issue by pogof** [teachingtechYT/teachingtechYT.github.io#296]
Im sure its mentioned somewhere that you should adjust the eccentric nuts on the Z ("X"?) axis. However if adjusted poorly (too tight or too loose you can get uneven results with ABL as one side of the axis is slightly behind the other one (on ender 3 for example where there is only one leadscrew). It was too tight and with my digital level measured only 0.1° difference, yet you could actually see it. After loosening the nut a bit all 5 squares look the same.

**Comment by teachingtechYT** [comment]
I agree with you. V rollers are mentioned on the frame check tab, which is mean to be followed before anything else.
![image](https://user-images.githubusercontent.com/8293825/125441780-774be9a9-833e-49bc-851b-0d6a3ad851d2.png)

**Comment by teachingtechYT** [comment]
I've added an extra sentence to that section to reflect your experiences.
