### ISSUE TITLE
Retraction speed test not performed correctly

### ISSUE THREAD

**Issue by schlagenkani** [teachingtechYT/teachingtechYT.github.io#298]
There is nothing in the GCode to change the firmware feedrate limit which prevents the correct execution of the retraction speed test.
For example, in Ender 3 we have DEFAULT_MAX_FEEDRATE { 500, 500, 5, 25 } which limits retraction speed to 25mm/s unless it's overridden by an M203 command.

**Comment by teachingtechYT** [comment]
Great observation.
I feel using M203 in my gcode to temporarily raise the limit will confuse users as their own prints won't match later on.
Therefore I've added an item to the important points section of the tab.
I will also highlight this in an upcoming video for the site.
