### ISSUE TITLE
Retraction calibration

### ISSUE THREAD

**Issue by prahjister** [teachingtechYT/teachingtechYT.github.io#30]
Might want to check out the retraction calibration I created. 
prahjister.duckdns.org

**Comment by teachingtechYT** [comment]
Someone raised this elsewhere. Much more powerful than mine but maybe overwhelming for beginners. A good compromise could be a link to your page for advanced users to follow?

**Comment by prahjister** [comment]
That is up to you. I am still tweaking and refining the process. I have had no issues but some people are. The few that have worked with me most turned out to be mechanical issues. We are working with one person and after turning s curve off started showing predictable normal results.

**Comment by teachingtechYT** [comment]
I've added it at the bottom, thanks for the link.
