### ISSUE TITLE
Retraction Calib only allows whole numbers

### ISSUE THREAD

**Issue by Ohmarinus** [teachingtechYT/teachingtechYT.github.io#31]
See title, it only allows you to input whole MM numbers so you cannot finetune, while in the example picture it clearly shows decimal values in the input boxes.

https://teachingtechyt.github.io/img/retractionresults.jpg

**Comment by bitfabrikken** [comment]
@Ohmarinus related to https://github.com/teachingtechYT/teachingtechYT.github.io/pull/29 ?

**Comment by teachingtechYT** [comment]
It is just a visual thing, you can type in whatever number you like. I've updated the form with steps to make it more convenient anyway.
