### ISSUE TITLE
support for alternate nozzle sizes

### ISSUE THREAD

**Issue by perfessor101** [teachingtechYT/teachingtechYT.github.io#311]
I'm calibrating a new filament for a 0.5 mm nozzle.
I can't see any options for this under first layer

if I missed it sorry

Nozzle size would help for calibration

**Comment by Deebatts** [comment]
Same here. I have my 0.4mm nozzle profiles tuned extremely well, but I find with 0.6 and 0.8 I have a much harder time dialing in retractions. I came to check the TT calibration site, as I'd found it helpful in getting several other settings dialed in. If this option exists I haven't been able to find it.

**Comment by teachingtechYT** [comment]
Duplicate but this feature is coming very soon.
