### ISSUE TITLE
can not print Baseline gcode on Anycubic Chiron

### ISSUE THREAD

**Issue by HelgeKeck** [teachingtechYT/teachingtechYT.github.io#312]
Hi,
the generated gcode for the baseline print prints only the first layer and then it doesnt extrude any filament anymore, it still does the movements, there is just no filament coming out.

Stock Anycubic Chiron V 1.3.0
Happens with and without Start Gcode.

these are the settigns im using.

Settings for baseline print form
_________________________________________________________________________

All changes are marked in the gcode with 'custom' at the end of each line. Open the gcode in a text editor and search for this to your inputs if needed.

Custom start gcode:
M104 S[first_layer_temperature] ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
M109 S[first_layer_temperature] ; wait for extruder temp
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
G1 Y0 F9001 ; go to front edge of the bed
G92 E0.0 ; reset extruder position
G1 X60.0 E9.0 F1000.0 ; intro line
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0 ; reset extruder position

Bed: 400 x 400 mm

Temperatures:
Bed: 60 deg C
Hot end: 215 deg C

Part Cooling: 100% fan from layer 2

ABL: No ABL

Retraction distance: 6 mm
Retraction speed: 40 mm/sec

**Comment by teachingtechYT** [comment]
Please import the generated gcode into your slicer and see if the preview looks as expected.
If it does, try printing the gcode over terminal so any error messages can be seen (or at least inspect the LCD for errors).
Not enough info here for me to determine if it's a problem wth my site otr your printer.
My last suggestion is for you to tick the box to remove the T0 command.
