### ISSUE TITLE
BLTouch guide should suggest minimum distance from heater block and safe operating temperatures

### ISSUE THREAD

**Issue by hitjim** [teachingtechYT/teachingtechYT.github.io#313]
Best I can find so far are the comments about bed temperature here: https://www.matterhackers.com/store/l/orbit-automatic-bed-leveling-probe/sk/MD32J6H7 - where it claims the plastic shouldn't go soft until 150C

Perhaps a silicone sock and/or kapton on the BLTouch would suffice, or otherwise protect in close quarters?

**Comment by teachingtechYT** [comment]
I'm all for suggesting a distance but I don't want to speculate and get the advice wrong. If Paris adds a recommendation to her BLtouch page I'll add the right info here too. Most users are constrained by the design of they mount they use, so perhaps the recommendation is better suited to the the mount designers.
At the moment I have this on the troubleshooting page:
![image](https://user-images.githubusercontent.com/8293825/125444943-4ab74c5c-3da0-4d9e-824d-f4a92e17d54a.png)
I'll copy that section about the heat to the general BLtouch page.

**Comment by hitjim** [comment]
Makes good sense. Thanks!
