### ISSUE TITLE
Is the Acceleration Gcode orriented correctly?

### ISSUE THREAD

**Issue by bassamanator** [teachingtechYT/teachingtechYT.github.io#316]
I'm not quite sure but it seems to me that the piece is not oriented correctly.

![accel-edit](https://user-images.githubusercontent.com/61985779/124096508-a6633a80-da28-11eb-8bb2-b2df1e75bb61.jpg)

Anycubic Mega S.

**Comment by teachingtechYT** [comment]
It is positioned correctly but this is not explained well. I will be addressing this this week.
