### ISSUE TITLE
Retraction Test scratched Bed (Anycubic Vyper)

### ISSUE THREAD

**Issue by davidh2k** [teachingtechYT/teachingtechYT.github.io#317]
I don't know why and how it happened, but the retraction testing unlinke the temperature testing scratched my Bed on my Anycubic Vyper. I'm by no means mad, though I found out that it seems that the gcode for the temp tower lifts the nozzle slightly higher than the retraction one does before moving to the center:

![image](https://user-images.githubusercontent.com/6970146/124403016-2ee92000-dd34-11eb-8b49-66042629ccdb.png)

![image](https://user-images.githubusercontent.com/6970146/124403224-89cf4700-dd35-11eb-92e1-d3e33a314fef.png)

Might be a very special issue with the Vyper that 'rests' the printhead below zero/to the side of the printbed.

Greetings
David

**Comment by teachingtechYT** [comment]
Hi David,
The retraction test gives you control over z hop whereas the other tests currently use a value of 0.4mm. I'm guessing you had the zhop at 0 for the retraction test, so yes the travel move will be lower.
0.2mm should be enough clearance so it may be worth checking your bed level, or a strange zero position of the nozzle as you have suggested.
