### ISSUE TITLE
Temperature Tower: first layer 

### ISSUE THREAD

**Issue by jigsawgirl** [teachingtechYT/teachingtechYT.github.io#32]
May I suggest that you add a variable to print the first layer (or base) of the Temperature Tower at the value of C. That way it will be a midrange temperature whether people print from low to high or high to low. The current settings may cause trouble with bed adhesion if people choose too low a temperature for the first layer.

BTW I love this website and imagine it will make tuning more accessible for new users.

**Comment by teachingtechYT** [comment]
That's a good idea, I will add to the to-do list.

**Comment by teachingtechYT** [comment]
Done!
