### ISSUE TITLE
Cura "spiralize outer contour" feature

### ISSUE THREAD

**Issue by TheRiflesSpiral** [teachingtechYT/teachingtechYT.github.io#321]
Hello,

I noticed the Slicer Flow Calibration section mentions using the "spiralize outer contour" setting (optionally) for printing the cube; Cura will over-extrude by about 20% when this setting is enabled, making the flow calculation under-extrude normal prints.

You can test this by printing the cube with that setting on/off, keeping the rest of the settings consistent. In my case, calibrating with spiralilze outer contour on with a 0.4mm nozzle resulted in a 0.52mm thickness wall. Changing only that setting results in a 0.41mm wall.

**Comment by teachingtechYT** [comment]
Well spotted. i will add a note about Cura. Thank you.
