### ISSUE TITLE
Visual studio code error when compiling marlin

### ISSUE THREAD

**Issue by Joost79** [teachingtechYT/teachingtechYT.github.io#322]
Not sure if this is the right place, forgive me I'm a noob...

I've watched your video and read the tutorial about compiling marlin 2.0 firmware for my ender 3d pro (on my 8bit v114 board). I've installed the visual studio, downloaded the marlin bugfix firmware and the correct example config.

Copied it to the right directory and loaded the directory in visual studio code on my windows 10 pc. So far no issues, and if i would just compile the firmware from there, everything works. But after i updated the original firmware to the settings as suggested in this page (https://teachingtechyt.github.io/upgrades.html#bltouch) and compile again, it fails every time, without exceptions.

I have quadruple checked everything and as far as i can find i have correctly removed all "//" and nothing more. Below is a screenshot of the issue;

![image](https://user-images.githubusercontent.com/87283307/125210676-9c9bcb80-e2a1-11eb-8968-fd0c64b3da30.png)

Any input would be greatly(!) appreciated, as seem unable to solve this issue.

**Comment by teachingtechYT** [comment]
This is completely unrelated to this site.

**Comment by Joost79** [comment]
My apologies, as i stated in my first sentence, i’m new to this.

So where should i go with this? My searches didn’t result in any answers.

Thanks

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: ***@***.***>
Verzonden: dinsdag 13 juli 2021 01:42
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [teachingtechYT/teachingtechYT.github.io] Visual studio code error when compiling marlin (#322)


This is completely unrelated to this site.
