### ISSUE TITLE
cr10max hemera upgrade lcd firmware  help

### ISSUE THREAD

**Issue by Tacodorifto** [teachingtechYT/teachingtechYT.github.io#331]
Thank you for all you do for the 3d print world.  I  recently purchased a Hemera upgrade for my Cr10 max  thanks to your guide. I have it installed wired.  I then tried the links on your youtube page  for the firmware and lcd updates. But they have changed from what your video shows and im lost.    It no longer has a dwinset for the lcd update. the file cr10spro max ender 5 plus v2 screen.7z  i also tried going to tiny machines to get the dwinset but that is not there either.   i have downloaded the arduino and that looks straight forward. thank you for any info and help.

**Comment by teachingtechYT** [comment]
This is not the place for this. Please don't spam this with personal technical support requests.
