### ISSUE TITLE
A Calibration Page(accel) needs a warning for z height before entering the first G code.

### ISSUE THREAD

**Issue by Rebar77** [teachingtechYT/teachingtechYT.github.io#332]
I was going through the Acceleration Tuning page on the Calibration Site and skipped the video because I wanted to read(oops!). Entered my G1 E50 F120 code and promptly bored PETG into my new magnetic surface. Tore a hole completely up when removing the glob. Doh! I guess I was expecting it to travel along the x or y for some reason... 

Still having my noob fun here but a warning to lift the nozzle from the home position will help the next person. 

Thanks a mil.

**Comment by teachingtechYT** [comment]
Add a sentence at the start. Thanks for the feedback.
