### ISSUE TITLE
BLTouch upgrade guide - optional changes - missing step in configuration_adv.h for babystep 

### ISSUE THREAD

**Issue by rruzicka** [teachingtechYT/teachingtechYT.github.io#341]
Need to uncomment #define BABYSTEPPING in order to use #define BABYSTEP_ZPROBE_OFFSET

**Comment by teachingtechYT** [comment]
From memory it was enabled by default for a while but I see that's no longer the case. I fix add an instruction and screenshot. Thanks very much.

**Comment by teachingtechYT** [comment]
Fixed, thanks again.
