### ISSUE TITLE
BUG - Inner/Outer Perimeter Speed

### ISSUE THREAD

**Issue by ThatGuyThatMakes** [teachingtechYT/teachingtechYT.github.io#346]
Inner and outer perimeter speeds are reversed on the acceleration tuning page https://teachingtechyt.github.io/calibration.html#accel

When creating a tuning model on the acceleration page, if I set inner perimeter speed to 30mm/s and outer perimeter to 20mm/s, the inner perimeter will print at 20mm/s while the outer will conversely print at 30mm/s.

**Comment by teachingtechYT** [comment]
Apparently I had this in reverse. Thanks for spotting, now fixed.
