### ISSUE TITLE
Retraction calibration gcode broken

### ISSUE THREAD

**Issue by NuClearArrow112** [teachingtechYT/teachingtechYT.github.io#35]
The retraction calibration test gcode came out odd-looking. I printed on an Anycubic Predator and on the second layer the hotend heating was turned off and the printer halted. That is why it has a blob on it. It never did such things.
I used decimals in the retraction distance values, so it might be an already mentioned issue.

![IMG_20200816_154059](https://user-images.githubusercontent.com/47058273/90336297-3d72ff80-dfdb-11ea-8be9-b654cf192760.jpg)
![IMG_20200816_154116](https://user-images.githubusercontent.com/47058273/90336299-449a0d80-dfdb-11ea-9aca-d64eb247ad36.jpg)
![Képernyőfelvétel (81)](https://user-images.githubusercontent.com/47058273/90336307-4a8fee80-dfdb-11ea-9c11-321eb11c37f4.png)
![Képernyőfelvétel (82)](https://user-images.githubusercontent.com/47058273/90336308-4b288500-dfdb-11ea-9d12-d6f9a0500efb.png)

**Comment by miklschmidt** [comment]
Can confirm, it's all over the place. Anycubic Kossel Pulley with Klipper here. Cura displays it the same way.
