### ISSUE TITLE
G-Code for base line 0.50mm nozzle and 0.30mm layer height is empty.

### ISSUE THREAD

**Issue by Petrogale0-0** [teachingtechYT/teachingtechYT.github.io#358]
Tested okay with 0.20mm and 0.35mm.

This was all it wrote:-
; G-Code originally generated by Simplify3D(R) Version 4.1.2
; This calibration test gcode modified by the Teaching Tech Calibration website: https://teachingtechyt.github.io/calibration.html
;M80 ; power supply on
G90
M82
M106 S0
M140 S50 ; custom bed temp
M190 S50 ; custom bed temp
M104 S190 T0 ; custom hot end temp
M109 S190 T0 ; custom hot end temp
G28 ; home all axes
;G29 ; probe ABL
;M420 S1 ; restore ABL mesh 
;customstart
G0 Z3; fix for delta printers that home at maxundefined
G28 X40.0000 ; home X axis
M106 S0 ; turn off cooling fan
M104 S0 ; turn off extruder
M140 S0 ; turn off bed
M84 ; disable motors
M501 ; restore previous EEPROM values
;customend

**Comment by teachingtechYT** [comment]
Fixed.
