### ISSUE TITLE
Please include IdeaMaker among slicer settings

### ISSUE THREAD

**Issue by nesdnuma** [teachingtechYT/teachingtechYT.github.io#360]
Hello,

There are places in the website where settings for several slicers are given, for instance in the _Slicer flow calibration_. It would be nice to include IdeaMaker too.

Thank you.

**Comment by nesdnuma** [comment]
This could help: [](https://3dprintbeginner.com/flow-rate-calibration/)

**Comment by teachingtechYT** [comment]
Agreed. Shouldn't be too hard to add but I don't have a specific timeframe.

**Comment by teachingtechYT** [comment]
This is now in place, with SuperSlicer added as well. Please reopen if I missed any parts, but I found: flow, retraction and acceleration tabs.

**Comment by nesdnuma** [comment]
Thank you!
