### ISSUE TITLE
Firefox Start Gcode

### ISSUE THREAD

**Issue by JRosello** [teachingtechYT/teachingtechYT.github.io#362]
Firefox 91.0.2 not show the _Additional Gcode Start_ box when the box is selected.
Tested in Chrome and it works so some issue with the page code with Firefox

**Comment by teachingtechYT** [comment]
I just installed 91.0.2 Firefox and I am unable to replicate:
![image](https://user-images.githubusercontent.com/8293825/132147489-e5a18faa-65c5-4400-beae-8bb9a8efd40a.png)
No errors in console either. I'm unable to shed any light at this stage but at least you have Chrome as a workaround.

**Comment by JRosello** [comment]
Find the issue, I have installed an extension called "EFF Privacy Badger" to block trackers, so seems that if I had enabled for your site prevents from opening the gcode box... weird

**Comment by teachingtechYT** [comment]
Glad you sorted it. This site doesn't use tracking cookies of any kind so that's very strange. The closest it does is store the values from the forms in the browser webstorage.
