### ISSUE TITLE
Add the ability to disable linear advance with retraction and other calibrations like jerk

### ISSUE THREAD

**Issue by emaayan** [teachingtechYT/teachingtechYT.github.io#363]
since Linear advance effects retraction, i think it should be possible to easily disable it (NOT enabling it cause you can just add M900 K0)  to avoid the possible noise

**Comment by teachingtechYT** [comment]
I don't think I'm understanding. As you say, M900 K0 in the start gcode disables LA so wouldn't the user just enter this into the custom start gcode box?
LA is probably worth a mention in the important notes section of that page.

**Comment by teachingtechYT** [comment]
This one seems to be stale and as far as I can tell is already supported by the site.
