### ISSUE TITLE
.5 mm nozzle .3 mm layer temperature tuning and retraction tuning no movement gcode in file

### ISSUE THREAD

**Issue by Dryice1049** [teachingtechYT/teachingtechYT.github.io#367]
When .5 mm nozzle and .3mm layer height are selected. It results in no movement gcode in the file, just start and end code. Only seems to happen with temperature and retraction tuning. 
[temperature.gcode.txt](https://github.com/teachingtechYT/teachingtechYT.github.io/files/7147799/temperature.gcode.txt)

**Comment by teachingtechYT** [comment]
I managed to export all of the 0.5 0.3mm gcode at the wrong layer height. THe other two tests have been fixed and now these two should be too. 
Thanks for spotting.
