### ISSUE TITLE
First Layer should raise nozzle between squares

### ISSUE THREAD

**Issue by micromouseonline** [teachingtechYT/teachingtechYT.github.io#376]
Can I suggest that the nozzle be raised by a couple of millimeters while traversing between squares in this test? As it is, the nozzle stays at printing height and drags across the square. Not a problem as such, just a neatness feature.

For example, I modified the code like this for the first square:
```
G1 Z2.000 F1200
G1 X14.6360 Y16.3140 F5000 ; custom feedrate
G1 Z0.200 F1200
```

**Comment by teachingtechYT** [comment]
Z hop under retraction is what you're looking for:
![image](https://user-images.githubusercontent.com/8293825/142706320-a6ee80c3-e87a-42d4-b840-e1b578ecdb18.png)
Please reopen if I've misunderstood.

**Comment by micromouseonline** [comment]
So it is - my mistake.
Thank you.
