### ISSUE TITLE
Add support for 0.35mm nozzle

### ISSUE THREAD

**Issue by gmsoft-tuxicoman** [teachingtechYT/teachingtechYT.github.io#379]
Hi,

The Velleman Vertex K8400 printer comes with a stock 0.35mm nozzle and those are not standard nozzle. It's therefor not possible to change it without changing the whole hotend.

Could you please add support for 0.35mm/0.2 layer height ?

Thank you !

**Comment by teachingtechYT** [comment]
Will do, hopefully this week.

**Comment by teachingtechYT** [comment]
Done :)
