### ISSUE TITLE
Incorrect origin in FlashPrint (with FlashForge Adventurer 4)

### ISSUE THREAD

**Issue by Kamholtz** [teachingtechYT/teachingtechYT.github.io#380]
Using a print bed size of 220mm x 200mm (x,y), I get the following when I import the first layer test gcode into Flashprint:

![image](https://user-images.githubusercontent.com/13547250/145509683-c977d2d3-0fbf-4491-b980-71495de316b4.png)

Enabling "0,0 at centre of bed" and setting the bed diameter to 200mm results in:

![image](https://user-images.githubusercontent.com/13547250/145509928-c13edefd-486f-4d19-b7fa-eb29abf26305.png)

I see similar results with the retraction gcode too.

**Comment by teachingtechYT** [comment]
The coordinates in the gcode are the coordinates in the gcode, the site doesn't do anything tricky here.
Therefore the printer must have strange coordinates. Can you confirm where 0,0 is on this printer?
Also, I'm confused by the twin preview shown above. Which is the actual preview and what is the other one?

**Comment by Kamholtz** [comment]
I'm unsure about the twin preview too. The colour of the right-most preview is what I observe when importing g-code from SuperSlicer, so I assume that's the actual print. There doesn't seem to be a way to determine what the left-most preview is (no hover tooltips or ability to inspect or click the preview).

As for the origin, it would appear that 0,0 is located at the front and centre of the bed. See the image below of the bed and the status menu showing the current coordinates:

![IMG_2549](https://user-images.githubusercontent.com/13547250/145698218-d7e19fa7-033d-427a-8aa7-6327bda55526.jpeg)

**Comment by teachingtechYT** [comment]
Thanks for the extra info. I've never seen origin point before in a 3D printer. Trying to think of a solution that doesn't clutter the interrface too much for the 99.9% of users who don't need and not too hard for me to implement. Maybe X/Y offset inputs to shift everything? That's essentially what the existing code is doing to suit different beds. I just have to make sure I don't break the base functionality in bringing this in.

**Comment by teachingtechYT** [comment]
Custom offset feature added. Most peole should leave this at 0,0 but in your case you should be able to adjust the position of the gcode on the bed to suit your printer.
