### ISSUE TITLE
is this a typo?

### ISSUE THREAD

**Issue by lmckeen** [teachingtechYT/teachingtechYT.github.io#40]
https://github.com/teachingtechYT/teachingtechYT.github.io/blob/master/js/gcodeprocessing.js#L227

this is the only similar line that doesnt have `TO` after the `home all axes/, "M109 S170`

**Comment by teachingtechYT** [comment]
It shouldn't be critical unless someone has a dual extrusion Prusa Mini but you are correct and I've updated as per your suggestion.
