### ISSUE TITLE
Acceleration Gcode generated without wait for bed temp

### ISSUE THREAD

**Issue by Max-Stevens** [teachingtechYT/teachingtechYT.github.io#49]
Gcode generates with M140 S{bed_temp} in two consecutive lines:
... 
M140 S{bed_temp}
M140 S{bed_temp}
...

rather than:
...
M140 S{bed_temp}
M190 S{bed_temp}
...

[acceleration.txt](https://github.com/teachingtechYT/teachingtechYT.github.io/files/5081661/acceleration.txt)

**Comment by teachingtechYT** [comment]
Fixed, thank you.
