### ISSUE TITLE
Typos... Acceleration tuning page multiple typos and errors

### ISSUE THREAD

**Issue by Andychud** [teachingtechYT/teachingtechYT.github.io#5]
**Bed Dimensions**
Is....
In the centre button is checked,

Should be...
If the centre button is checked,

**Part Cooling Fan**
Is....
PLA typically has the part cooling fan come o n from layer 2. Alter thi default bahaviour here:

Should be....
PLA typically has the part cooling fan come on from layer 2. Alter this default behaviour here:

**Comment by teachingtechYT** [comment]
Got the, thank you.
