### ISSUE TITLE
Strange characters in Prusa Mini display when printing retraction.gcode

### ISSUE THREAD

**Issue by Gei0r** [teachingtechYT/teachingtechYT.github.io#53]
Hi,

when printing `retraction.gcode`, I have some strange characters where the "remaining time" is displayed:

![mini](https://user-images.githubusercontent.com/16615274/90421226-5a7e0000-e0b9-11ea-9e5c-bf1bc9f6feaa.jpg)

I don't know if this is actually a problem with the gcode or the Prusa Mini, though.

**Comment by teachingtechYT** [comment]
My guess is the Prusa Mini uses some custom gcode for progress which is not provided by this gcode. As long as the print continues I think it would be safe to ignore.
