### ISSUE TITLE
[Missing information] Add Cura/ Prusa/ Slicer custom parameters

### ISSUE THREAD

**Issue by OlivierMary** [teachingtechYT/teachingtechYT.github.io#6]
Hi again,

Some or all slicers like prusaslicer, cura, ... have in theirs configurations feedrate, jerk, acceleration, .... parameters, so if change it in Marlin with M500 it's override by generated GCode.

Maybe add in each pages the place of the parameters in commons slicers. (For many of slicers it's a little hidden, have to switch to expert mode or choose all parameters visible)

Thanks again for your work :)

**Comment by teachingtechYT** [comment]
I will add notes, thanks for raising this.

**Comment by teachingtechYT** [comment]
Done.
