### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by Guizz27** [teachingtechYT/teachingtechYT.github.io#62]
I was looking a little bit at the code and I saw something like this in the retraction
    retraction = retraction.replace(/G1 E-6.0000 F900/g, "G1 E-"+a1+" F"+a2);
    retraction = retraction.replace(/G1 E0.4000 F900/g, "G1 E"+a3+" F"+a2);
    // B section
    retraction = retraction.replace(/G1 E-7.0000 F1200/g, "G1 E-"+b1+" F"+b2);
    retraction = retraction.replace(/G1 E0.6000 F1200/g, "G1 E"+b3+" F"+b2);

the problem is if someone enters the value 7 in section A, then the code above will replace the 6 by 7, then replace the 7 by the value entered in section B resulting in section A and B be the same. I know the feed rate would also have to match which makes this issue not likely to happen. But I'm assuming there is similar code in other places.

A better approach is to use placeholders in the original gcode. So if in the original gcode you replace "G1 E-6.0000 F900" by something like "G1 E-<a1> F<a2>" then the code could do: 
    retraction = retraction.replace(/<a1>/g, a1);
    retraction = retraction.replace(/<a2>/g, a2);
or in a single replace as you have
    retraction = retraction.replace(/G1 E-<a1> F<a2>/g, "G1 E-"+a1+" F"+a2);

The first example above could be used to add a comment section at the beginning of the gcode with all the selected values from the web form.

You could even replace the whole line in the original gcode by something like "<retract-section-a>" then in the code you would do 
    retraction = retraction.replace(/<retract-section-a>/g, "G1 E-"+a1+" F"+a2);

**Comment by teachingtechYT** [comment]
A similar system was recently added for the temperature test and I have just implemented something very similar to that and your suggestion. Thanks for the heads up.
