### ISSUE TITLE
Further Explanation needed for Set Ups

### ISSUE THREAD

**Issue by AvionicsKen** [teachingtechYT/teachingtechYT.github.io#67]
I have never hooked up my printers to the PC. Just a stock boar, stock firmware, and  SD guy. (Ender3pro Anet A8)

1)If there are tab steps that cannot be perform due to someone that has only stock boards and firmware, it should be clearly stated.

2)If I were to tether my printers to cura, would I be able to accomplish the firmware modifications?

**Comment by teachingtechYT** [comment]
The only firmware modification needed is for linear advance. This is stated in the video and on the website. A video is embedded on the linear advance page that goes over firmware changes required. So what you are asking for is already in place.

I think the confusion comes from the talk of using a terminal. In this case, the software is linked in the tools section of the tab. All that is required is to connect the 3d printer and computer with the USB cable, select the COM port (which is suggested by the software), baud rate (which is also pre-selected) and click connect. Even if it sounds hard, once you try it you'll find it really easy. No firmware changes or bootloader required.

I am happy to add further instruction on this, but it may clog up the top of the page. Any suggestions for doing so in a way that keeps things clean?
