### ISSUE TITLE
[Feature Request] - Option for Nozzle size

### ISSUE THREAD

**Issue by macgyverK9** [teachingtechYT/teachingtechYT.github.io#69]
HI Team

First I have to say thank you, All calibration for your machine in one place. I am eternally grateful and appreciate the effort put forth.

I have several machines, I am suspecting that most of the code here is designed for a .4 Nozzle. Is there any way to add the option of different nozzle sizes, personally I print with .4, .5, .6 and .8. I am suspecting some of my calibrations are off because of the nozzle size.

Any chance we could see a nozzle size option in the calibration options?

Thanks again for all the hard work you did on this, Its awesome.

**Comment by teachingtechYT** [comment]
It will be happening but will take some time.
#1
