### ISSUE TITLE
A request for the temp tower

### ISSUE THREAD

**Issue by matthew2018** [teachingtechYT/teachingtechYT.github.io#76]
Could the tower design involve a stringing test, so when you temp test your filament you can see the temp least stringing before going to the retraction test to refine it further.

So far is a great idea and great help for calibrating printers thank you

**Comment by teachingtechYT** [comment]
This is actually already built into the model. The two side are completely separate apart from the small bridge at the top of each segment. Effectively, it recreates the geometry from the stringing test so it should communicate what you are after.
