### ISSUE TITLE
[Suggestion] Convert G-code to JSON for easier manipulation

### ISSUE THREAD

**Issue by tseven** [teachingtechYT/teachingtechYT.github.io#77]
Firstly I'd like to thank you all for creating this guide, it's fantastic and is exactly what our community needed! 

I can see many benefits to converting the G-code to a JSON object instead of performing REGEX find and replace.

[This javascript library](https://www.npmjs.com/package/gcode-json-converter) will do the trick.

This way you can loop through the object and easily modify the values of the specific G-code commands you'd like while avoiding the complexity of regex.

I have not studied code used for the calibration page enough to know if this is feasible but thought I'd throw it out there.

**Comment by teachingtechYT** [comment]
As a programmer I'm self taught and no doubt a professional could do things a lot more elegantly.
When creating the site I probably would have gone with this suggestion but now that everything is established and working, I don't want to rewrite and risk more bugs creeping in.
Thanks for the suggestion, however.
