### ISSUE TITLE
feature request - show the input values in generated gcode as comments

### ISSUE THREAD

**Issue by tommy-kc** [teachingtechYT/teachingtechYT.github.io#78]
for those of us with poor memory...
in the generated GCODE put in comments either at the top (best) or inline for the retraction test (for example) to say what options were selected when the gcode was generated.

I'm getting older, it feels like a lot older... and I have a hard time remembering what I did in the first test.  If I can go back to the file that was generated and see what my input values were in the table then I'd be very very happy!

Thanks
Tom

**Comment by teachingtechYT** [comment]
This has recently been implemented, just not as the top of the file. Open in a text editor and search for the word 'custom' Everything is labelled, including segment A, B, C, etc where relevant.
Values are now persistent on the forms too, so even if you close your browser, when you return the values are still there to reference.
