### ISSUE TITLE
Value Issue on the temperature tuning section

### ISSUE THREAD

**Issue by kromeninja** [teachingtechYT/teachingtechYT.github.io#79]
Hi! Firstly I really like this tool and I'm sure its going to be a great help for many so thank you for putitng the time into this!

One minor issue I have found with the temperature tuning section is that I cannot add a decimal place for my retraction disstance that was set in the previous section "retraction tuning". 

![Temp_Tuning_Value_Issue](https://user-images.githubusercontent.com/41597316/90851845-d011f680-e36d-11ea-8dae-e8c05d57d7b9.png)

**Comment by teachingtechYT** [comment]
Fixed, thanks for finding it and posting.
