### ISSUE TITLE
Modifiers for different nozzle sizes.

### ISSUE THREAD

**Issue by jhenley01** [teachingtechYT/teachingtechYT.github.io#8]
Hello,

This is an awesome project, thank you for creating this. I mostly use a 0.6 nozzle so some of the tests did not print correctly for me, it would be awesome to have options for different nozzle sizes. Thanks again!

**Comment by Andychud** [comment]
I use 0.6 too and agree 100% that there should be option to select different nozzle sizes.

**Comment by Andychud** [comment]
I just noticed that this has already been requested/reported
https://github.com/teachingtechYT/teachingtechYT.github.io/issues/1#issue-679402188

**Comment by jhenley01** [comment]
> I just noticed that this has already been requested/reported
> [#1 (comment)](https://github.com/teachingtechYT/teachingtechYT.github.io/issues/1#issue-679402188)

Ah good call, somehow I did not see that. Closing.
