### ISSUE TITLE
Feature Request: Export Settings to TXT

### ISSUE THREAD

**Issue by thehirsches** [teachingtechYT/teachingtechYT.github.io#85]
I would really like the ability to export the current settings to a txt file for reference later.

Hot end temperature (deg C): 200
Bed temperature (deg C): 70
Speed and any other settings

Segment
Retraction distance (mm)
Retraction speed (mm/sec)
Extra restart distance (mm)
Prime (unretract) speed (mm/sec)
Z hop (mm)

F-5-25-0-25-0
E-6-25-0-25-0
D-7-25-0-25-0

**Comment by teachingtechYT** [comment]
This one is close, just getting the details worked out.

**Comment by teachingtechYT** [comment]
Implemented :)
