### ISSUE TITLE
PID Tuning: from cool end? cooling fans on?

### ISSUE THREAD

**Issue by jaredgrubb** [teachingtechYT/teachingtechYT.github.io#89]
I have read two things about PID tuning:
 - you want to start from a room temperature part
 - you want to manually turn on the cooling fans

Is this true?

**Comment by teachingtechYT** [comment]
Done.

**Comment by Deses** [comment]
I think you sould put the note about turning the fan ON and load some filament BEFORE all the steps, because I wonder how many people do all the steps only to have to do it again because they didn't have the fan turned on.

Like myself. lol
