### ISSUE TITLE
Retraction Tuning - collision on delta

### ISSUE THREAD

**Issue by onne1951** [teachingtechYT/teachingtechYT.github.io#95]
G1 X-31.128 Y-12.959000000000003 F6000

in the beginning of the gcode is making my Anycubic Predator (delta) crashing into the top

Same problem with Temperature Tuning

**Comment by teachingtechYT** [comment]
Do you think this is related to the long floating point? Y-12.959000000000003
Can you please manual edit the first few occurrences in the gcode to round to less decimal places to confirm it is this and not something else?
Eg. Y-12.959000000000003 to Y-12.959

**Comment by onne1951** [comment]
should never be negative due to the fact that Y is already at the top, minus makes it go into the ceiling

**Comment by teachingtechYT** [comment]
Typically a delta has a centre point of 0,0, which means many negative values. If yours does not, don't tick the 

> 0,0 at centre of bed 

box and instead input your bed diameter for X and Y.

This is why the instructions say to preview the gcode first, it's aimed at avoiding collisions.
